### ISSUE TITLE
NowButton plugin error in Zim 0.72

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1010]
On MacOS, running Zim via `python3 zim.py -D` generally works. However, the NowButton plugin cannto be loaded, resulting in the following error message:
```
ERROR: Could not load plugin nowbutton
Traceback (most recent call last):
  File "/Users/floriankrause/Downloads/zim-0.72.1/zim/gui/preferencesdialog.py", line 361, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/Users/floriankrause/Downloads/zim-0.72.1/zim/plugins/__init__.py", line 415, in get_plugin_class
    mod = get_module(modname)
  File "/Users/floriankrause/Downloads/zim-0.72.1/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/Users/floriankrause/.local/share/zim/plugins/nowbutton.py", line 20, in <module>
    from zim.plugins import PluginClass, WindowExtension, extends
ImportError: cannot import name 'WindowExtension' from 'zim.plugins' (/Users/floriankrause/Downloads/zim-0.72.1/zim/plugins/__init__.py)
```

**Comment by bgmilne** [comment]
The API for plugins seems to have changed with the port to Gtk3 (along with the changes to the Gtk3 APIs).

Please report this to the plugin author.

**Comment by introt** [comment]
This seems to be a plugin issue, not a Zim one.
