### ISSUE TITLE
Zim does not start on OpenSuSE Tumbleweed

### ISSUE THREAD

**Issue by vyrgozunqk** [zim-desktop-wiki/zim-desktop-wiki#1036]
Hi guys,

Zim is refusing to start at all on a new install of Opensuse Tumbleweed. I've install almost the entire Python3.8 package and all its gtk dependencies.  Libgtk-3(and it's 32 bit version) is also installed. All deps according to Zim's website are also installed. 
It looks like it's unable to find something, but I'm not a dev...

This is the output I receive:

 zim 
Traceback (most recent call last):
  File "/usr/bin/zim", line 40, in <module>
    import zim.main
  File "/usr/lib/python3.8/site-packages/zim/main/__init__.py", line 31, in <module>
    from zim.notebook import Notebook, Path, \
  File "/usr/lib/python3.8/site-packages/zim/notebook/__init__.py", line 38, in <module>
    from .info import NotebookInfo, NotebookInfoList, \
  File "/usr/lib/python3.8/site-packages/zim/notebook/info.py", line 18, in <module>
    from .notebook import NotebookConfig, _resolve_relative_config
  File "/usr/lib/python3.8/site-packages/zim/notebook/notebook.py", line 17, in <module>
    import zim.templates
  File "/usr/lib/python3.8/site-packages/zim/templates/__init__.py", line 61, in <module>
    from zim.templates.functions import build_template_functions
  File "/usr/lib/python3.8/site-packages/zim/templates/functions.py", line 24, in <module>
    from zim.formats.html import html_encode
  File "/usr/lib/python3.8/site-packages/zim/formats/__init__.py", line 79, in <module>
    from zim.plugins import PluginManager
  File "/usr/lib/python3.8/site-packages/zim/plugins/__init__.py", line 45, in <module>
    from zim.actions import hasaction
  File "/usr/lib/python3.8/site-packages/zim/actions.py", line 36, in <module>
    PRIMARY_MODIFIER_MASK = _get_modifier_mask()
  File "/usr/lib/python3.8/site-packages/zim/actions.py", line 30, in _get_modifier_mask
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

**Comment by quatran** [comment]
I had the same problem ( #976 ) and the problem was resolved by installing the packages
`gtk3-devel` and` python3-gobject-Gdk`

**Comment by stappersg** [comment]
@vyrgozunqk does installing those packages solve the issue you reported?

If yes, say so and please close the issue.  (Open issues do drain human energy)

**Comment by vyrgozunqk** [comment]
@stappersg sorry, I really couldn't try it. The suggestion came way too late. I had to install Kubuntu 19.10. I really needed ZIM for my database at work and couldn't afford to loose time. Maybe someone else could try it...

**Comment by NHamata** [comment]
@stappersg @quatran 
Had the same issue as OP, this was fixed by installing the dependencies listed
You can probably just close this issue, as well as #976

**Comment by introt** [comment]
Closing - please open a new issue if the problem persists with 0.74
