### ISSUE TITLE
Windows - "Go -> Today (Alt + D)" results in path not found error

### ISSUE THREAD

**Issue by jaks6** [zim-desktop-wiki/zim-desktop-wiki#1050]
When trying to go to journal's "today" page, by clicking menubar -> Go -> Today, the following error is produced:

`The system cannot find the path specified: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\babel\locale-data/*.*`

OS: Windows 10
Zim version: Zim 0.69.1
Installation version: through installer

**Comment by ironfroggy** [comment]
I found this issue after running into the same problem. I reproduced it in debug mode and got this from the log:

```
DEBUG: Action: go_page_today
DEBUG: Exception during action: go_page_today
Traceback (most recent call last):
  File "zim\actions.pyo", line 157, in do_activate
  File "zim\actions.pyo", line 140, in func
  File "zim\plugins\calendar.pyo", line 246, in go_page_today
  File "zim\plugins\calendar.pyo", line 131, in path_from_date
  File "zim\datetimetz.pyo", line 167, in weekcalendar
  File "zim\datetimetz.pyo", line 87, in init_first_day_of_week
  File "babel\core.pyo", line 166, in __init__
  File "babel\localedata.pyo", line 50, in exists
  File "babel\localedata.pyo", line 35, in normalize_locale
  File "babel\localedata.pyo", line 62, in locale_identifiers
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Zim Desktop Wiki\\zim.exe\\babel\\locale-data/*.*'
ERROR: The system cannot find the path specified: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\babel\locale-data/*.*
DEBUG: Running ErrorDialog
```

I also found that of the two machines I installed Zim Wiki 0.69.1 to, I only got this error on one and I looked for the difference. I found that on one machine I had set the Journal plugin's "Use a page for each:" parameter set to "Week". Day, Month, and Year settings do not cause this error when invoking Alt+D.

**Comment by jaks6** [comment]
Some time has passed, I am now running Zim on a new machine, still Windows 10, but noticed that now as of Zim 0.73.5, the bug seems to have disappeared.
