### ISSUE TITLE
'View Log' in 'Edit Equation' does not work

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#1110]
Version 0.73.0

When I entered a bad equation, press 'Preview' and then 'View Log'. No log dialog popped up.

Here the backtrace:
```
INFO: Running: ('latex', '-no-shell-escape', '-halt-on-error', 'equation.tex') (cwd: '/tmp/zim-d8szeth0')
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/plugins/base/imagegenerator.py", line 326, in <lambda>
    self.logbutton.connect('clicked', lambda o: self.show_log())
  File "/usr/lib/python3.8/site-packages/zim/plugins/base/imagegenerator.py", line 358, in show_log
    assert self.logfile, 'BUG: no logfile set (yet)'
AttributeError: 'ImageGeneratorDialog' object has no attribute 'logfile'
```

**Comment by Nick222** [comment]
Sample of "bad equation", pls.

Windows? Linux?

**Comment by cheese** [comment]
Just any equation that does not compile.

Always reproducible, tested on Fedora 32.

**Comment by Nick222** [comment]
INFO: Running: ('latex', '-no-shell-escape', '-halt-on-error', 'equation.tex') (cwd: '/tmp/zim-wtyjjyxe')
INFO: Running: ('dvipng', '-q', '-bg', 'Transparent', '-T', 'tight', '-o', '/tmp/zim-wtyjjyxe/equation.png', '/tmp/zim-wtyjjyxe/equation.dvi') (cwd: None)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 326, in <lambda>
    self.logbutton.connect('clicked', lambda o: self.show_log())
  File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 358, in show_log
    assert self.logfile, 'BUG: **no logfile set (yet)**'
AttributeError: 'ImageGeneratorDialog' object has no attribute 'logfile'
