### ISSUE TITLE
navigation left pane does not open right pane, sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#1189]
zim 0.72.1
OS: MX Linux  18.4
Python 2.7.13 

the notebook is writable & I can toggle it
but 
clicking on left pane item does not update right pane,
this fail happens over time, the function does work when starting the notebook but over time (unknown how long yet)
the notebook shows this error
zim -D

sqlite3.OperationalError: attempt to write a readonly database

I'll toggle read-write
DEBUG shows

DEBUG: Action: toggle_editable(True)
DEBUG: Action: toggle_editable(False)
DEBUG: Action: toggle_editable(True)
INFO: Open page: Health:chiro NS (Health:chiro NS)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 421, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4986, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 777, in open_page
    self.notebook.index.check_async(self.notebook, paths, recursive=False)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 175, in check_async
    self._checker.queue_check(file, recursive=recursive)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 324, in queue_check
    (STATUS_CHECK, path, STATUS_CHECK)
sqlite3.OperationalError: attempt to write a readonly database

closing zim reports

DEBUG: Action: close (delete-event)
DEBUG: Remove window: AppIndicatorTrayIcon
DEBUG: Remove window: MainWindow

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(zim:24482): Gtk-CRITICAL **: 09:08:51.904: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
DEBUG: Remove window: AppIndicatorTrayIcon
DEBUG: Last toplevel destroyed, quit

**Comment by galenthurber** [comment]
0.73.2 same issue
sqlite3.OperationalError: attempt to write a readonly database

INFO: Open page: Home:cordless (Home:cordless)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 444, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5165, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 789, in open_page
    self.notebook.index.check_async(self.notebook, paths, recursive=False)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 175, in check_async
    self._checker.queue_check(file, recursive=recursive)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 324, in queue_check
    (STATUS_CHECK, path, STATUS_CHECK)
sqlite3.OperationalError: attempt to write a readonly database
INFO: Open page: Home:cell phone sharon (Home:cell phone sharon)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 444, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5165, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 789, in open_page
    self.notebook.index.check_async(self.notebook, paths, recursive=False)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 175, in check_async
    self._checker.queue_check(file, recursive=recursive)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 324, in queue_check
    (STATUS_CHECK, path, STATUS_CHECK)
sqlite3.OperationalError: attempt to write a readonly database
INFO: Open page: Home:cell tower mapper (Home:cell tower mapper)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 444, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5165, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 789, in open_page
    self.notebook.index.check_async(self.notebook, paths, recursive=False)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 175, in check_async
    self._checker.queue_check(file, recursive=recursive)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 324, in queue_check
    (STATUS_CHECK, path, STATUS_CHECK)
sqlite3.OperationalError: attempt to write a readonly database
INFO: Open page: Home:cordless (Home:cordless)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 444, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5165, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 789, in open_page
    self.notebook.index.check_async(self.notebook, paths, recursive=False)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 175, in check_async
    self._checker.queue_check(file, recursive=recursive)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 324, in queue_check
    (STATUS_CHECK, path, STATUS_CHECK)
sqlite3.OperationalError: attempt to write a readonly database

**Comment by jaap-karssenberg** [comment]
Looks like the database file does not have the right permissions. Please
check whterhe the "index.db" file is writable.

-- Jaap

**Comment by galenthurber** [comment]
/home/galen/Dropbox/Notebooks/shared/.zim/
ls -al
no files
that's a problem

odd, some my other notebooks have an index.db file

**Comment by jaap-karssenberg** [comment]
If the "shared" property is enabled, you would find these files under
~/.cache/zim (or relative to XDG_CACHE_DIR if set).

-- Jaap

**Comment by galenthurber** [comment]
yes, the db is there
permission is RW user, correct

**Comment by introt** [comment]
Are you still having this problem on the latest version?

**Comment by galenthurber** [comment]
yes

**Comment by introt** [comment]
No worries @galenthurber (tagging for notifications).

> /home/galen/Dropbox/Notebooks/shared/.zim/
> ls -al
> no files
> that's a problem
>
> odd, some my other notebooks have an index.db file 

Did I understand correctly that this issue is only present on notebooks saved to Dropbox, and notebooks saved elsewhere work? If so, this sounds to be related to Dropbox.

Please attach a debug log from the latest version (0.74.3) and let us know your current OS, Dropbox client & Python versions. Thanks!

**Comment by galenthurber** [comment]
I've since switched to Google drive.
I did notice that Zim creates a .Zim folder and the files are dated (for my setup) 2015
They are not updating

**Comment by introt** [comment]
@galenthurber Your issue sounds similar to #1991. Are you sure that the `shared` property is enabled in each notebook's `notebook.zim` (`shared=True` under `[Notebook]`)? Again, is the issue present with both local-only notebooks, or only the ones you're trying to sync with Google Drive?

Try deleting all the cache folders (all the `.zim`s, you can use `find ~ -type d -name '.zim'` to locate them, as well as `~/.cache/zim`) and starting Zim from the terminal with the `-D` flag. If you're still having the issue, please post full logs as well as the versions of your OS and Google Drive client so we may attempt to replicate the issue.

**Comment by galenthurber** [comment]
thanks.
I run zim in shared mode
my gdrive client, is opengrive (I've tested it with it off)
I run zim with -D option
I've deleted cache before, no effect

I store my notebooks in home
/Google Drive/Notebooks/
one called shared 
/Google Drive/Notebooks/shared
.zim has no files
Google Drive/Notebooks/shared/.zim/no files/

find ~ -type d -name '.zim'
finds nothing

I did find ~/.cache/zim folders
I deleted them again
I will monitor for problems

**Comment by introt** [comment]
Hi @galenthurber, thanks for the response. I wasn't able to track down "opengrive" - where did you install it from?

At this point I must also confess that it's not really clear to me what exactly you're having an issue with. Have you been able to both edit your notes and upload them to Google Drive? I'm assuming the problems haven't stopped you from using Zim, since you haven't switched away.

Some screenshots illustrating the problem would be appreciated. Right now I can only guess what you've configured your panes to show, or what it is that should be updating but isn't.

**Comment by introt** [comment]
So based on your comments on issues #1417 and #1562, you can resume editing files after restarting Zim, correct?

**Comment by galenthurber** [comment]
yes I can resume editting after zim is completely closed
kill the terminal that ran zim -D
or killall zim
if run from XFCE menu

**Comment by introt** [comment]
> I store my notebooks in home
/Google Drive/Notebooks/

To find out whether the issue is related to the cloud storage software, could you create a new notebook **outside** `Google Drive`, in a path that doesn't contain spaces, and see if the error happens there?

I'd also like to see the output of `df -a` - the cloud storage directory might have some weird FUSE mount.
