### ISSUE TITLE
Zim doesn't startup if python3 is python3.7

### ISSUE THREAD

**Issue by joereynolds** [zim-desktop-wiki/zim-desktop-wiki#1218]
I have upgraded python from python 3.6 to python 3.7.
After this upgrade I get the following:

```
: zim
Traceback (most recent call last):
  File "/usr/local/bin/zim", line 50, in <module>
    import zim.main
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/usr/lib/python3/dist-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/usr/lib/python3/dist-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/zim", line 50, in <module>
    import zim.main
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/usr/lib/python3/dist-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/usr/lib/python3/dist-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zim", line 52, in <module>
    sys.excepthook(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/zim", line 50, in <module>
    import zim.main
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/usr/lib/python3/dist-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/usr/lib/python3/dist-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zim", line 52, in <module>
    sys.excepthook(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

I have worked around this issue for now by changing this line in `/usr/local/bin/zim` from
```
#!/usr/bin/python3
```
and to a working fixed version instead

```
#!/usr/bin/python3.6
```

**Comment by jaap-karssenberg** [comment]
I think there is something wrong in your install of the python gi package.
Maybe re-install that one as well with your python3.7 environment ?
