### ISSUE TITLE
Cannot start zim on windows

### ISSUE THREAD

**Issue by Chimrod** [zim-desktop-wiki/zim-desktop-wiki#1277]
Hello,

I have a problem when running zim on windows (I've used the package zim-desktop-wiki-0.73.2-setup.exe).

When I run the binary, nothing occurs. In the log, it seems that the path to the library is not correctly set up : zim tries to load the library in `D:\lib\…` instead of `D:\my_zim_install\lib\…`

[zim.exe.log](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/5296964/zim.exe.log)

**Comment by jaap-karssenberg** [comment]
Weird, certainly does not happen on my own systems when testing.

If anyone has a clue under which conditions this happens, please comment.

-- Jaap

**Comment by PitifulDragon** [comment]
I am having a similar issue - although I can't find a log. I get a popup every time I launch "Fatal error detected. Failed to execute zim_launch. I get this on both 73.2 and 73.1 (Windows 10)

**Comment by mheden** [comment]
I have the same problem with a windows portable installation 0.73.3. I don't get a log or anything. Tried to look at a procmon dump of the start but it looks similar to when I start my 0.68 portable install so no clues there. Seems to work fine with the "non portable" install though.

**Comment by musamaanjum** [comment]
I'm facing the same issue after installing 0.73.4 version on Windows 10. With normal privileges, it always gives the error, "failed to execute script zim_launch". It executes fine if I open with admin privileges though.

**Comment by musamaanjum** [comment]
Everything was gloomy until I decided to restart the Windows and miraculously it is working without even administrator privileges. So the solution is to restart the Windows after installing the zim.

**Comment by DvP17** [comment]
I have the same issue with Zim 0.73.5 (zim-desktop-wiki-0.73.4-setup-w64_x86.exe). Zim does not start, but I can see that Zim opens up as a background process. This issue occurred after I installed the KB5001330 Windows 10 Update update.

Are there any solutions or workarounds available yet?

**Comment by dlavor** [comment]
Same issue in my environment. Used to work fine but I cannot say for sure what changed in time. Runs fine elevated.

zim.exe log:

Traceback (most recent call last):
  File "zim_launch.py", line 130, in <module>
  File "zim_launch.py", line 103, in main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:/msys64/home/jaap karssenberg/zim-desktop-wiki/windows/build/venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "zim/__init__.py", line 191, in <module>
  File "os.py", line 675, in __getitem__
KeyError: 'USERNAME'

**Comment by jaap-karssenberg** [comment]
Sounds like something either upstream or out of our control.

**Comment by dlavor** [comment]
> Sounds like something either upstream or out of our control.

dont rely on sysenv USERNAME and use different method for getting logged user on Windows

**Comment by jaap-karssenberg** [comment]
The problem is that "USERNAME" is a windows specific fallback. Not really
sure what to use if it is not set.

-- Jaap

**Comment by theoky** [comment]
I am just setting up a new machine for myself and encountered this behavior as well. I did a little research and stumbled upon this link;
[%username% is unavailable in Windows that has OneDrive for Business installed](https://docs.microsoft.com/en-us/troubleshoot/windows-client/ue-v/percent-username-percent-unavailable)

I'm using OneDrive for Business, so this could very well be the reason. After setting this registry entry mentioned in the link it seems to work for me without elevation.
> Per user OneDrive installation
> [HKEY_CURRENT_USER\SOFTWARE\Microsoft\OneDrive] "HasSystrayIconBeenPromoted"=dword:00000001
 
hope that helps someone.

**Comment by mavensecurity** [comment]
I already has the "Per user" reg setting so I had to add the "Per computer" option suggested in https://docs.microsoft.com/en-us/troubleshoot/windows-client/ue-v/percent-username-percent-unavailable

**Per computer OneDrive installation**
`[HKEY_CURRENT_USER\SOFTWARE\Microsoft\OneDrive] "HasPerMachineSystrayIconBeenPromoted"=dword:00000001`

**Comment by NaoPross** [comment]
> Zim does not start anymore, but I can see that Zim opens up as a background process.

I had a similar issue on Windows 11 after connecting to a docking station with monitors. In this case the problem that something had put the zim window outside of the screen coordinates. To check if this is happening to you / to fix it you can look at the cache config 

`%APPDATA%\zim\cache\zim\notebook_XXX\state.conf`

and check the very first key `MainWindow.windowpos`. Mine was at 10k or  something like that, outside of the screen), I could restart Zim after resetting this to `(0,0)`. I suppose clearing the cache (i.e. deleting the folder) might also fix it.

Perhaps when reloading the cached state Zim should check that the window is not outside of the screen, even though in principle this should be dealt with by the window manager.

**Comment by krisztianmukli** [comment]
> check the very first key `MainWindow.windowpos`. Mine was at 10k or something like that, outside of the screen), I could restart Zim after resetting this to `(0,0)`. I suppose clearing the cache (i.e. deleting the folder) might also fix it.

I did that for a while, then I found that it's faster to hold the mouse over the open zim icon in the taskbar, then the preview of the window appears, right click on it then click to small size in the menu, then right click again then click to previous size (sometimes just the previous size works by itself).

Otherwise, yes, the Mainwindow.windowpos coordinates you mentioned are lost if I use it on multiple monitors (e.g. with a docking station at work) and then use it in single monitor mode. Maybe it should be reported as a bug...

**Comment by archfrog** [comment]
I couldn't get my Zim v0.76.3 to open on my 3440x1440 monitor until I used your trick to right-click the preview and select `Minimize` then `Maximize`.  I'm not sure the `Minimize` part was necessary, but this is a great and quick fix for a rather surprising situation :-)

Edit: I just had the problem again and this time only selected `Maximize`.  That fixed the problem and Zim reappered.
