### ISSUE TITLE
readonly database error, 0.68

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#1327]
the error is back
I've reverted to a fresh install of MX Linux
and 0.68
unable to find previous bug reports

This is zim 0.68
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 16, 'final', 0)
Gtk: (2, 24, 32)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 814, in open_page_back
    self.open_page(record)
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 730, in open_page
    raise AssertionError('Could not close page')
AssertionError: Could not close page

**Comment by jaap-karssenberg** [comment]
Can you add a bit more context on when this error happens? The error
message itself does not mention the database, why do you think it is read
only database error?

Op vr 20 nov. 2020 16:58 schreef Galen Thurber <notifications@github.com>:

**Comment by galenthurber** [comment]
system is MX 19.3

zim popup window

This is zim 0.68
Platform: posix
Locale: en_CA UTF-8
FS encoding: UTF-8
Python: (2, 7, 16, 'final', 0)
Gtk: (2, 24, 32)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/widgets.py", line 3211, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2578, in do_response_ok
    self.app_window.ui.open_page(page)
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 733, in open_page
    self.notebook.index.touch_current_page_placeholder(path)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/__init__.py", line 278, in touch_current_page_placeholder
    pid = self.update_iter.pages.insert_link_placeholder(path)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 170, in insert_link_placeholder
    return self._insert_page(pagename, True)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 196, in _insert_page
    (pagename.name, sortkey, parent_row['id'], is_link_placeholder, file_id)
OperationalError: attempt to write a readonly database

**Comment by galenthurber** [comment]
zim is my main information program

OperationalError: attempt to write a readonly database
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/gui/pageindex.py", line 406, in do_page_activated
    self.ui.open_page(path)
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 730, in open_page
    raise AssertionError('Could not close page')
AssertionError: Could not close page

**Comment by introt** [comment]
Hi, please open a new issue if you're still having this problem on a version newer than 0.70. Thanks!

**Comment by galenthurber** [comment]
I have reexamined a possible cause of this read-only error, I use MX linux and it includes a daily cron task that clears ~/.cache
This task seems to run at differing times of the day. I had assumed it only ran at the start of day. I think it can be triggered by returning a sleep mode from xscreensaver. This made it hard to track down the R/O lock up cause. Since removing this cron task  zim has not failed with Read Only error on this one machine. I will test on other my other MX machines when I get access to them

**Comment by introt** [comment]
What an interesting decision from the MX Linux devs! I guess we could make the caching more robust against surprise runtime deletions, but that's such an edge case that I don't think its worth the effort for now. Glad to hear the issue was resolved!

**Comment by dehesselle** [comment]
Deleting a cache folder during normal operation/without caring if programs are using it is a bug in the OS and should be reported there.
