### ISSUE TITLE
Bug or not ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1329]
Xubuntu 20.10
zim 0.73.4
Python 3.8.6

Appear error-window ("PyObject is NULL").

Debug log from Zim:

> INFO: This is zim 0.73.4
> DEBUG: Python version is sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
> DEBUG: Platform is posix
> DEBUG: Not running from a source dir
> DEBUG: Set XDG_DATA_HOME to ~/.local/share
> DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/xubuntu>, <Dir: /usr/share/xfce4>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /var/lib/snapd/desktop>, <Dir: /var/lib/snapd/desktop>, <Dir: /usr/share>]
> DEBUG: Set XDG_CONFIG_HOME to ~/.config
> DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-xubuntu>, <Dir: /etc/xdg>, <Dir: /etc/xdg>]
> DEBUG: Set XDG_CACHE_HOME to ~/.cache
> DEBUG: Start listening on: /run/user/1000/zim-0.73.4-e63203e4
> DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f54cdcefe50>
> DEBUG: Loading config from: ~/.../notebook.zim
> DEBUG: Loading config from: ~/.../notebook.zim
> DEBUG: Loading config from: ~/.cache/zim/notebook-.../state.conf
> DEBUG: New extendable: <zim.notebook.notebook.Notebook object at 0x7f54cdc5c940>
> DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookExtension'>
> DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListNotebookExtension'>
> DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
> INFO: VCS detected: git - ~/...
> DEBUG: Loading config from: <ConfigFile: ~/.config/zim/style.conf>
> DEBUG: Autosave interval: 10 - use threads: True
> DEBUG: New extendable: <pageview.PageView object at 0x7f54cdc29e00 (zim+gui+pageview+PageView at 0x1b24700)>
> DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
> DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.journal.JournalPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.linkmap.LinkMapPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
> DEBUG: Spellcheck language: ru_RU
> DEBUG: requesting name for code "en_ZA"
> DEBUG: requesting name for code "ru_RU"
> DEBUG: requesting name for code "en_GB"
> DEBUG: requesting name for code "en_US"
> DEBUG: requesting name for code "ru"
> DEBUG: requesting name for code "en_AU"
> DEBUG: requesting name for code "en"
> DEBUG: requesting name for code "en_CA"
> DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.tags.TagsPageViewExtension'>
> DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListPageViewExtension'>
> DEBUG: Action: toggle_panes(False)
> DEBUG: Action: toggle_panes(True)
> ...
> DEBUG: Action: new_sub_page
> DEBUG: Opening dialog "New page..."
> DEBUG: Dialog response OK
> INFO: Loading template from: ~/.local/share/zim/templates/wiki/Default.txt
> DEBUG: Store page: ...
> INFO: Running: ('git', 'add', '....txt') (cwd: '~/...')
> DEBUG: Index file: ~/.../....txt
> INFO: Open page: ...
> DEBUG: Closed dialog "New page..."
> DEBUG: BackgroundCheck started
> 
> (zim:150395): Gtk-CRITICAL **: 02:13:12.175: ../../../../gtk/gtktreeview.c:6953 (do_validate_rows): assertion `gtk_tree_model_iter_next (tree_view->priv->model, &iter)' failed.
> There is a disparity between the internal view of the GtkTreeView,
> and the GtkTreeModel.  This generally means that the model has changed
> without letting the view know.  Any display from now on is likely to
> be incorrect.
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_value_type_compatible: assertion 'src_type' failed
>   return _Gtk_main(*args, **kwargs)
> 
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'weight' of type 'gint' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'sensitive' of type 'gboolean' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'style' of type 'PangoStyle' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'text' of type 'gchararray' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 248, in do_get_path
>     path = self.on_get_path(self.get_user_data(iter))
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> 
> (zim:150395): Gtk-CRITICAL **: 02:13:12.368: gtk_tree_path_to_string: assertion 'path != NULL' failed
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 248, in do_get_path
>     path = self.on_get_path(self.get_user_data(iter))
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> 
> (zim:150395): Gtk-CRITICAL **: 02:13:12.377: gtk_tree_path_to_string: assertion 'path != NULL' failed
> DEBUG: BackgroundCheck found out-of-date

**Comment by jaap-karssenberg** [comment]
Clearly a bug. Please add a bit more information on when it occurs, how to reproduce etc. And please change the title to describe the bug.

**Comment by Nick222** [comment]
In Firefox 83.0 and addon for Firefox Zim-clip 1.3 copy information about page https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1329.
Create page "11111" and paste information in it.
And then edit page in Zim.

**Comment by Nick222** [comment]
Information for copy:

```
======  ======
@(тэг)
Ключевые слова: 

Автор: 
Название: Bug or not ? · Issue #1329 · zim-desktop-wiki-zim-desktop-wiki
Носитель: web
Тип: object обзор
Публикатор: github.com

Описание: Xubuntu 20.10 zim 0.73.4 Python 3.8.6 Appear error-window ("PyObject is NULL"). Debug log from Zim: INFO: This is zim 0.73.4 DEBUG: Python version is sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0) DEBUG: Plat...

Дата:  / Дата: 
ISBN: нет
Место: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1329

Запись: нет
Копия: нет

Источник: нет
Также: нет
Примечания: нет

```

**Comment by Nick222** [comment]
And Zim-clip did not work at a month (do not open Zim and create page automatically) - it`s author cannot understand - why...

**Comment by Nick222** [comment]
Run "zim -- debug" and do https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1329#issuecomment-731844671

While editing "11111" page I see this:

> (zim:85712): Gtk-CRITICAL **: 00:00:24.085: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed

and then - while continue editing - this:
(I cut automatically created date information from second line and paste it in another place)
(Or - may be - it simple need only some time)

> (zim:85712): Gtk-CRITICAL **: 00:01:27.749: ../../../../gtk/gtktreeview.c:6953 (do_validate_rows): assertion `gtk_tree_model_iter_next (tree_view->priv->model, &iter)' failed.
> There is a disparity between the internal view of the GtkTreeView, and the GtkTreeModel.  This generally means that the model has changed without letting the view know.  Any display from now on is likely to be incorrect.

And after few minutes without user activity - I see full error message (see my first post).

**Comment by Nick222** [comment]
Need more information?

**Comment by Nick222** [comment]
Any page...

1) Write 
> @sample
and (Enter)

2) (Ctrl-S)

3) Go to another application. Wait a minute or less - and in Zim-terminal:

> 
> Index file: /.../1234567.txt
> 
> (zim:161586): Gtk-CRITICAL **: 20:07:56.049: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
> 
> (zim:161586): Gtk-CRITICAL **: 20:08:01.739: ../../../../gtk/gtktreeview.c:6953 (do_validate_rows): assertion `gtk_tree_model_iter_next (tree_view->priv->model, &iter)' failed.
> There is a disparity between the internal view of the GtkTreeView,
> and the GtkTreeModel.  This generally means that the model has changed
> without letting the view know.  Any display from now on is likely to
> be incorrect.
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_value_type_compatible: assertion 'src_type' failed
>   return _Gtk_main(*args, **kwargs)
> 
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'weight' of type 'gint' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'sensitive' of type 'gboolean' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'style' of type 'PangoStyle' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> WARNING: /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: unable to set property 'text' of type 'gchararray' from value of type '(null)'
>   return _Gtk_main(*args, **kwargs)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 248, in do_get_path
>     path = self.on_get_path(self.get_user_data(iter))
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> 
> (zim:161586): Gtk-CRITICAL **: 20:08:01.949: gtk_tree_path_to_string: assertion 'path != NULL' failed
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 257, in do_get_value
>     return self.on_get_value(self.get_user_data(iter), column)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 60, in wrapped_func
>     return func(*args, **kargs)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 248, in do_get_path
>     path = self.on_get_path(self.get_user_data(iter))
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 156, in get_user_data
>     return _get_user_data_as_pyobject(iter)
>   File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/generictreemodel.py", line 46, in _get_user_data_as_pyobject
>     return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
> ValueError: PyObject is NULL

**Comment by jaap-karssenberg** [comment]
Cannot reproduce on my system. Looks like your index is out of sync. You
can rebuild it with "zim --index NOTEBOOK" - hope that helps.

-- Jaap

**Comment by Nick222** [comment]
Some month ago I **manually** add txt-file in Notebook folder.
But this txt-file name has symbol " in it.

Now when I try to do:

zim --index NOTEBOOK

I receive:

> ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x7f951b1ccac0>
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/signals.py", line 365, in emit
>     r = handler(self, *args)
>   File "/usr/lib/python3/dist-packages/zim/notebook/index/pages.py", line 109, in on_file_row_inserted
>     pagename, file_type = self.layout.map_filepath(filerow['path'])
>   File "/usr/lib/python3/dist-packages/zim/notebook/layout.py", line 125, in map_filepath
>     Path.assertValidPageName(name)
>   File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 138, in assertValidPageName
>     raise AssertionError('Not a valid page name: %s' % name)
> AssertionError: Not a valid page name: ...
> ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x7f951b1ccac0>
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/signals.py", line 365, in emit
>     r = handler(self, *args)
>   File "/usr/lib/python3/dist-packages/zim/notebook/index/pages.py", line 129, in on_file_row_changed
>     pagename, file_type = self.layout.map_filepath(filerow['path'])
>   File "/usr/lib/python3/dist-packages/zim/notebook/layout.py", line 125, in map_filepath
>     Path.assertValidPageName(name)
>   File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 138, in assertValidPageName
>     raise AssertionError('Not a valid page name: %s' % name)
> AssertionError: Not a valid page name: ...

Then I delete " from this file name - and indexing finish without errors.

But error (above) do not dissapeared - and Giggle and gitg crashed when I try to open my notebook`s versions in it.

**Comment by Nick222** [comment]
May be add command "Check filenames of zim-files" ?

And - VCS-programs cannot normal work with codepage "UTF-8 with BOM" - may be add checking BOM codepage in zim-files ?

**Comment by Nick222** [comment]
Reproducing:

1) Create empty notebook
2) Open it
3) In "Home" page after(!) title create 2 empty lines - by <Enter> !
4) Return 1 line up by <Up>
5) Write "@" and any symbols without space
6) Do not push <Enter> !!! Go to next line by <Down>
7) Save <Ctrl-S>

Error...

Plugin Zim-clip and some other plugins - switch-off.
