### ISSUE TITLE
Can't copy and paste linked text with snapshot version

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1488]
I can't copy and paste text any more when it's linked to a URL (a link to another Zim page works though), after upgrading to [0.73.5-SNAPSHOT-t202106031854~ubuntu20.10.1](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots?field.series_filter=groovy). Copying a full URL, not linked within a text, doesn't work either.

**Comment by sojusnik** [comment]
Here's the log, showing when I copy an URL and try to paste it:

```
~$ zim -D
Gtk-Message: 22:19:53.250: Failed to load module "appmenu-gtk-module"
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x7fba889bcca0>
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: tableeditor
DEBUG: Load extension: <class 'zim.plugins.tableeditor.TableViewObjectType'>
DEBUG: register_object: "table"
DEBUG: Loading plugin: versioncontrol
DEBUG: Loading plugin: tableofcontents
DEBUG: Loading plugin: distractionfree
DEBUG: Loading plugin: bookmarksbar
DEBUG: Loading plugin: tags
DEBUG: Loading plugin: spell
DEBUG: Loading plugin: zim-zotero-plugin
DEBUG: Loading plugin: tagcomplete
DEBUG: Loading plugin: linkmap
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: copy-rich
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: linesorter
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: attachmentbrowser
INFO: This is zim 0.73.5
DEBUG: Python version is sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/sojusnik/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/gnome-xorg>, <Dir: /home/sojusnik/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/sojusnik/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-gnome-xorg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/sojusnik/.cache
DEBUG: Connecting to /run/user/1000/zim-0.73.5-e63203e4
DEBUG: Got error in dispatch: No such file or directory
WARNING: Could not find all icon sizes for the application icon
DEBUG: Starting primary process
DEBUG: Start listening on: /run/user/1000/zim-0.73.5-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7fba89132d60>
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/state.conf
DEBUG: New extendable: <Notebook: Allgemeines>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: VCS detected: git - /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/style.conf>
DEBUG: Autosave interval: 10 - use threads: True
INFO: Page changed on disk: Entwürfe
INFO: Open page: Entwürfe (Entwürfe)
DEBUG: New extendable: <notebookview.NotebookView object at 0x7fba85b88fc0 (zim+gui+notebookview+NotebookView at 0x148aaf0)>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linesorter.LineSorterPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linkmap.LinkMapPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tags.TagsNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.zim-zotero-plugin.ZoteroPageViewExtension'>
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7fba85b4ed00 (zim+gui+mainwindow+MainWindow at 0x1454270)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.copy-rich.RichCopyWindow'>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.tagcomplete.TagAutocompleteWin'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
INFO: Running: ('git', 'status', '--porcelain') (cwd: '/home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines')
DEBUG: No autosave version needed - no changes
DEBUG: Accelmap: /home/sojusnik/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: copy
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 4200, in do_button_release_event
    self.click_link() or self.click_checkbox() or self.click_anchor()
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 4683, in click_anchor
    pixbuf = self._get_pixbuf_at_pointer(iter, coords)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 4554, in _get_pixbuf_at_pointer
    pixbuf = iter.get_pixbuf()
AttributeError: 'NoneType' object has no attribute 'get_pixbuf'
DEBUG: Action: paste
DEBUG: Targets available for paste: [Gdk.Atom.intern("TIMESTAMP", False), Gdk.Atom.intern("TARGETS", False), Gdk.Atom.intern("MULTIPLE", False), Gdk.Atom.intern("SAVE_TARGETS", False), Gdk.Atom.intern("UTF8_STRING", False), Gdk.Atom.intern("COMPOUND_TEXT", False), Gdk.Atom.intern("TEXT", False), Gdk.Atom.intern("STRING", False), Gdk.Atom.intern("text/plain;charset=utf-8", False), Gdk.Atom.intern("text/plain", False)], we want parsetree
DEBUG: Requesting data for ('text/x-zim-parsetree', 0, 1) -- using set_with_data() workaround
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 4126, in do_paste_clipboard
    self.get_buffer().paste_clipboard(Clipboard, None, self.get_editable(), text_format=format)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 3362, in paste_clipboard
    parsetree = clipboard.get_parsetree(self.notebook, self.page, text_format)
  File "/usr/lib/python3/dist-packages/zim/gui/clipboard.py", line 797, in get_parsetree
    return parsetree_from_selectiondata(selectiondata, notebook, path, text_format)
  File "/usr/lib/python3/dist-packages/zim/gui/clipboard.py", line 245, in parsetree_from_selectiondata
    parsetree.replace(
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 668, in replace
    self._replace(self._etree.getroot(), tags, func)
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 685, in _replace
    self._replace(child, tags, func) # recurs
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 679, in _replace
    replacement = func(Element.new_from_etree(child))
  File "/usr/lib/python3/dist-packages/zim/gui/clipboard.py", line 369, in _strip_link_and_image_attribs
    node.attrib.pop('_href')
KeyError: '_href'

```

**Comment by jaap-karssenberg** [comment]
Thanks for the error log - will fix it

**Comment by sojusnik** [comment]
Thanks, works after the update!
