### ISSUE TITLE
Problem to load sourceview plugin on Ubuntu 18.04 with last release 0.74

### ISSUE THREAD

**Issue by Digitalin** [zim-desktop-wiki/zim-desktop-wiki#1591]
Hi,

Thank you for this beautiful piece of software that goes along with me for ten years. 
I am on Xubuntu 18.04.3 and the last release works so far, and except the CSD decoration issue already mentioned, I met a error with sourceview. 

![windows-plugins-Preferences](https://user-images.githubusercontent.com/12547689/133754643-6eeef135-d1a5-4ec1-b14c-bf957657f426.png)

I tried to deactivate all plugins to see, without success. 
Version of packages : 
- python3: Installé : 3.6.7-1~18.04
- gir1.2-gtk-3.0: Installé : 3.22.30-1ubuntu4
- python3-gi: Installé : 3.26.1-2ubuntu1
- python3-xdg: Installé : 0.25-4ubuntu1.1
- libgtksourceview-3.0-1 :  Installé : 3.24.7-1
- libgtksourceview-3.0-common: Installé : 3.24.7-1
- xdg-utils: Installé : 1.1.2-1ubuntu2.5

Is there other lib for sourceview to install ? All was ok on 0.73.5

**Comment by jaap-karssenberg** [comment]
There seem to be two issues which I would like to bundle in this issue
1. your report that deps fail, even if they shouldn't
2. several reports I received of this plugin misbehaving even though the
pre-requisites did not change

Both suggest something went wrong with loading sourceview 3.0. Intended
behavior is to always try 3.0 first and only as a fallback use version 4.
But looks like loading 3.0 fails anyway :(

Needs investigation

Regards,

Jaap

**Comment by jaap-karssenberg** [comment]
P.S. please check the error log (or run using "zim -D" to see output), when
opening the preferences errors could be reported that are relevant

**Comment by Digitalin** [comment]
Here the error log

`DEBUG: BackgroundCheck started
DEBUG: Action: show_preferences
ERROR: Could not load plugin sourceview
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/preferencesdialog.py", line 402, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 459, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3/dist-packages/zim/utils.py", line 36, in get_module
    mod = __import__(name)
  File "/home/$USER/.local/share/zim/plugins/sourceview.py", line 28, in <module>
    from zim.utils import WeakSet
ImportError: cannot import name 'WeakSet'
DEBUG: Loading description for plugin: arithmetic
DEBUG: Opening dialog "Préférences"
DEBUG: Loading description for plugin: sourceview
`

**Comment by jaap-karssenberg** [comment]
In that case I was in error bundling these issues. Need new ticket for the
sourceview rendering issues.

In this case the log shows it tries to load a plugin from ".local" which is
out of date, please remove it and the default plugin from the distribution
should be loaded.

-- Jaap

**Comment by Digitalin** [comment]
I removed the sourceview.p* and now its works well. Thank you

Just to be sure, the $XDG_DATA_HOME   = HOME/.local/share/ is still relevant for Zim plugins and templates ?

**Comment by brainbow1** [comment]
I also had problems with rendering somehow... couldnt really find the origin of it though. Just a few thoughts/documentation of mine:

On my debian system, zim is in the official repositories in version: 0.73.5-1
On my Ubuntu system it is in version 0.72.0-1

After the new versions 0.74 was installed via deb package on both devices I had these problems. First I thought it was gtksourceview but:

I removed zim on both devices and installed again:

debian: zim 0.73.5-1 from the official repos
ubuntu: zim 0.73.5-1 from the deb-all .deb-package from ur website
Because I knew that this old version always worked, I tried with that, and now it works perfectly well on both machines.......

My conclusion for now: I stick to 0.73.5-1..

A few hours later:
The rendering thing started again, but only occasionally. Restarting of zim SOMETIMES helps, but not always.
PS: I use Ubuntu 20.04LTS with Xfce and Debian 11 with Xfce.

**Comment by Digitalin** [comment]
@ brainbow1 
I revert back to 7.3.5 as well for the rendering problem when scrolling and for decoration too. I will test next release to see but this one is a stable release, at least for Debian like with Xfce

**Comment by brainbow1** [comment]
thanks for the feedback!
I just found out that I have both packages installed under Debian 11
libgtksourceview-3.0-1
libgtksourceview-4-0

could it have to do something with that? If yes, which of the both packages should I keep and which one should I purge?

**Comment by Simplenuity** [comment]
Here also quite massive rendering problems to the point page/Zim is not usable anymore. As @brainbow1 described, sometimes restart helps but not always. The more the page has code blocks, headings, etc. the bigger are the rendering problems. 

OS: Linux Lite 4.8 (based on Ubuntu 18.04)
Zim: 0.74.0-t202109161818~ubuntu18.04.1
(only) libgtksourceview-3.0-1 installed

Happy to provide more info if you let me know what exactly will be helpful to troubleshoot?

**Comment by dehesselle** [comment]
@brainbow1 No, having both versions 3 and 4 of libgtksourceview doesn't change anything for you. Zim will stick to version 3 as it always has. Only in case that version 3 is missing, Zim >= 0.74 will try to use version 4.
