### ISSUE TITLE
txt/text file attachment crashes exporter (b/c it tries to parse it as a wiki page)

### ISSUE THREAD

**Issue by Osndok** [zim-desktop-wiki/zim-desktop-wiki#164]
This might be something that I can fix myself, but I'm not sure of the best strategy:
* A partial fix might be to try to avoid attachment TXT files from appearing in the export page iterator (by matching the name of the directory it is in; except for root pages)
* An option to ignore the error ("--best-effort" or "--force")
* Try and fix the parser to... well... parse anything
* "fallback" to file-copying if parser fails, but (maybe) still return a non-successful exit code

```
ERROR: Exception in signal handler for process on <zim.templates.Template object at 0x7f2a60595650>
Traceback (most recent call last):
  File "/mnt/projects/zim-desktop-wiki/zim/signals.py", line 338, in emit
    r = handler(self, *args)
  File "/mnt/projects/zim-desktop-wiki/zim/templates/__init__.py", line 186, in do_process
    processor.process(output, context)
  File "/mnt/projects/zim-desktop-wiki/zim/templates/processor.py", line 81, in process
    self.__call__(output, self.main, context)
  File "/mnt/projects/zim-desktop-wiki/zim/templates/processor.py", line 130, in __call__
    self._loop(output, element, context)
  File "/mnt/projects/zim-desktop-wiki/zim/templates/processor.py", line 169, in _loop
    self.__call__(output, element, context) # recurs
  File "/mnt/projects/zim-desktop-wiki/zim/templates/processor.py", line 111, in __call__
    value = expr(context)
  File "/mnt/projects/zim-desktop-wiki/zim/templates/expression.py", line 124, in __call__
    value = getattr(value, p)
  File "/mnt/projects/zim-desktop-wiki/zim/export/template.py", line 488, in title
    return self.heading or self.basename
  File "/mnt/projects/zim-desktop-wiki/zim/export/template.py", line 431, in heading
    head, body = self._split_head()
  File "/mnt/projects/zim-desktop-wiki/zim/export/template.py", line 462, in _split_head
    tree = self._tree.copy()
  File "/mnt/projects/zim-desktop-wiki/zim/formats/__init__.py", line 330, in copy
    return ParseTree().fromstring(xml)
  File "/mnt/projects/zim-desktop-wiki/zim/formats/__init__.py", line 307, in fromstring
    parser.feed(string)
ParseError: not well-formed (invalid token): line 35, column 5
ERROR: Could not read: /path/to/Notebook/Page/SubPage/attachment.txt
```

**Comment by Osndok** [comment]
Or maybe the more obvious (but **HARD**) solution would be to switch to a non-conflicting file extension, like "*.zim" or "*.wiki"... ?

**Comment by jaap-karssenberg** [comment]
Known issue - solution is planned by checking page headers.

Does it crash the full export process, or just for this page?

**Comment by BehindTheBrain** [comment]
Just a note that the non-conflicting file-extension works with a singe-character change (easy): notebook/layout.py: default_extension = '.txt' to whatever you like.

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * This concrete error is fixable in export code
  * Port "head" operation to token representation while at it
  * Then close this issue but link to generic item for ignoring non-page text files

**Comment by myrdd** [comment]
FYI my workaround is to use `.text` instead of `.txt`. it's still recognized as `text/plain`.

oh! I just discovered that there is the `text/x-zim-wiki` mimetype, great!

```
> file *
non-zim.txt:         ASCII text
zim.txt:             text/x-zim-wiki, ASCII text, with CRLF line terminators
```

**Comment by jaap-karssenberg** [comment]
Closing this issue by fixing the actual crash that starts the thread. Opened a new issue #907 to track fix in indexer to completely ignore non-page text files.
