### ISSUE TITLE
Image properties menu entry disappeared after update

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1658]
Before updating to 0.74.1-SNAPSHOT-t202110021808~ubuntu21.04.1 it was possible to right-click on an image to edit its properties, but now this right-click menu entry is missing.

**Comment by sojusnik** [comment]
Seems to be connected: Right-clicking on images in the attachment-browser plugin isn't possible either.

**Comment by jaap-karssenberg** [comment]
Works fine for me. Can you check the debug log and give a more specific
example or screenshot ?

**Comment by sojusnik** [comment]
When right-clicking on a picture, then this is shown:

```
$ zim -D
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x7f4ca64fb7f0>
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: tableeditor
DEBUG: Load extension: <class 'zim.plugins.tableeditor.TableViewObjectType'>
DEBUG: register_object: "table"
DEBUG: Loading plugin: versioncontrol
DEBUG: Loading plugin: tableofcontents
DEBUG: Loading plugin: bookmarksbar
DEBUG: Loading plugin: spell
DEBUG: Loading plugin: zim-zotero-plugin
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: tags
DEBUG: Loading plugin: linkmap
DEBUG: Loading plugin: attachmentbrowser
DEBUG: Loading plugin: distractionfree
DEBUG: Loading plugin: copy-rich
DEBUG: Loading plugin: linesorter
DEBUG: Loading plugin: commandpalette
DEBUG: Loading plugin: tagcomplete
DEBUG: Loading plugin: instantsearch
INFO: This is zim 0.74.1
DEBUG: Python version is sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/sojusnik/.local/share
DEBUG: Set XDG_DATA_DIRS to [<LocalFolder: /usr/share/gnome-xorg>, <LocalFolder: /home/sojusnik/.local/share/flatpak/exports/share>, <LocalFolder: /var/lib/flatpak/exports/share>, <LocalFolder: /usr/local/share>, <LocalFolder: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/sojusnik/.config
DEBUG: Set XDG_CONFIG_DIRS to [<LocalFolder: /etc/xdg/xdg-gnome-xorg>, <LocalFolder: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/sojusnik/.cache
DEBUG: Connecting to /run/user/1000/zim-0.74.1-e63203e4
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /run/user/1000/zim-0.74.1-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f4c9e215f70>
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Connecting to database file: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/index.db
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/state.conf
DEBUG: New extendable: <Notebook: Allgemeines>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: VCS detected: git - /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/style.conf>
DEBUG: Autosave interval: 10 - use threads: True
INFO: Page changed on disk: Entwürfe:Test
INFO: Open page: Entwürfe:Test (Entwürfe:Test)
DEBUG: New extendable: <notebookview.NotebookView object at 0x7f4c9e16b440 (zim+gui+notebookview+NotebookView at 0x263aae0)>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linesorter.LineSorterPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linkmap.LinkMapPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tags.TagsNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.zim-zotero-plugin.ZoteroPageViewExtension'>
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7f4c9e224a40 (zim+gui+mainwindow+MainWindow at 0x25b4500)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.commandpalette.CommandPaletteMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.copy-rich.RichCopyWindow'>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.instantsearch.InstantSearchMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.tagcomplete.TagAutocompleteWin'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
INFO: Running: ('git', 'status', '--porcelain') (cwd: '/home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines')
DEBUG: No autosave version needed - no changes
DEBUG: Accelmap: /home/sojusnik/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6576, in do_populate_popup
    self._default_do_populate_popup(menu)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6739, in _default_do_populate_popup
    dir = file.dir
AttributeError: 'LocalFile' object has no attribute 'dir'
```

**Comment by sojusnik** [comment]
And this is shown, when right-clicking on an image in the attachments browser:

```
…
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/attachmentbrowser/filebrowser.py", line 380, in on_button_press_event
    self.do_populate_popup(popup_menu, pathinfo)
  File "/usr/lib/python3/dist-packages/zim/plugins/attachmentbrowser/filebrowser.py", line 404, in do_populate_popup
    submenu = OpenWithMenu(window, file) # XXX any widget should do to find window
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 1023, in __init__
    for entry in manager.list_applications(mimetype):
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 495, in list_applications
    add_entry(basename, _application_dirs())
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 482, in add_entry
    file = _application_file(basename, dirs)
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 52, in _application_file
    file = dir.file(p)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 191, in file
    return LocalFile(self.get_childpath(path), watcher=self.watcher)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 311, in get_childpath
    assert path
AssertionError
```

**Comment by jaap-karssenberg** [comment]
Ah sorry - missed that you are looking at the development branch. Error
message is helpful for fixing it.

**Comment by sojusnik** [comment]
Something similar happens, when right-clicking on a link, where the corresponding menu entries like edit or copy link are missing:

```
…
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6576, in do_populate_popup
    self._default_do_populate_popup(menu)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6739, in _default_do_populate_popup
    dir = file.dir
AttributeError: 'LocalFile' object has no attribute 'dir'
```
