### ISSUE TITLE
[develop] Links to local folders don't open

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1661]
After updating to `0.74.1-SNAPSHOT-t202110051858~ubuntu21.04.1` (could also be 1-2 releases earlier), links to local folders don't open, while links to local files still work.

`zim -D` shows:
```
…
DEBUG: Activate link: ~/Sonstiges/Smartphone/Sync/Pictures/Screenshots
DEBUG: open_file(/home/sojusnik/Sonstiges/Smartphone/Sync/Pictures/Screenshots, None)
DEBUG: Exception during activate-link(('~/Sonstiges/Smartphone/Sync/Pictures/Screenshots', {'new_window': False}))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6511, in do_activate_link
    self._do_activate_link(link, hints)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6525, in _do_activate_link
    open_file(self, path)
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 549, in open_file
    raise FileNotFoundError(file)
zim.newfs.base.FileNotFoundError: No such file or folder: /home/sojusnik/Sonstiges/Smartphone/Sync/Pictures/Screenshots
ERROR: No such file or folder: /home/sojusnik/Sonstiges/Smartphone/Sync/Pictures/Screenshots
DEBUG: Running ErrorDialog
```
The path is correct and the folder does exist.

**Comment by sojusnik** [comment]
Always a pleasure!
– your personal bug hunter :)
