### ISSUE TITLE
Cannot copy text including paths across multiple pages

### ISSUE THREAD

**Issue by e3rd** [zim-desktop-wiki/zim-desktop-wiki#1764]
**Describe the bug**
Cannot copy path.

```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 6627, in <lambda>
    item.connect('activate', lambda o: self.textview.do_paste_clipboard(format='verbatim'))
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 4141, in do_paste_clipboard
    self.get_buffer().paste_clipboard(Clipboard, None, self.get_editable(), text_format=format)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 3376, in paste_clipboard
    parsetree = clipboard.get_parsetree(self.notebook, self.page, text_format)
  File "/usr/lib/python3/dist-packages/zim/gui/clipboard.py", line 641, in get_parsetree
    return parsetree_from_selectiondata(selectiondata, notebook, path, text_format)
  File "/usr/lib/python3/dist-packages/zim/gui/clipboard.py", line 228, in parsetree_from_selectiondata
    replace_parsetree_links_and_copy_images(parsetree, notebook, path)
  File "/usr/lib/python3/dist-packages/zim/notebook/content_updater.py", line 94, in replace_parsetree_links_and_copy_images
    parsetree.replace(
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 668, in replace
    self._replace(self._etree.getroot(), tags, func)
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 685, in _replace
    self._replace(child, tags, func) # recurs
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 690, in _replace
    self._do_replace(elt, replacements)
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 705, in _do_replace
    newchild = self._node_to_etree(node)
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 729, in _node_to_etree
    node.visit(builder)
  File "/usr/lib/python3/dist-packages/zim/formats/__init__.py", line 1557, in visit
    item.visit(visitor)
AttributeError: 'NoneType' object has no attribute 'visit'
```

**To Reproduce**
1. Write a path starting a slash, like /tmp or /dev/video0. (Plain text, URls, formatted text, tags work well.)
2. Copy the text including the path.
3. Go to any other page.
4. Hit Ctrl+V, nothing happens, nothing is pasted. Error output in the terminal appears.
5. Go back to the original page. Hitting Ctrl+V pastes the text.

**Expected behavior**
I should be able to copy and paste the text including paths accross the pages of a notebook.

**Screenshots**

I write a path.

![image](https://user-images.githubusercontent.com/6942231/143450232-adc7a127-e079-4982-991c-e8cd17950e72.png)

I copy the text via Ctrl+C.

![image](https://user-images.githubusercontent.com/6942231/143450279-0c16f576-200d-4732-a4d6-b3fedd0433a5.png)

I go to any other page and hit Ctrl+V. *Nothing happens.* An error log is produced in the terminal. However, if I go back to the original page, I may use Ctrl+V as usual.

![image](https://user-images.githubusercontent.com/6942231/143450567-135ad2f9-6492-439d-88b0-8b2d15955a82.png)

**Environment (please complete the following information):**
 - Version [e.g. 0.74.2] -- the development branch
 - OS: Linux Ubuntu 20.10.
 - Language: English locale

**Comment by jaap-karssenberg** [comment]
Can reproduce with master, not with develop branch. Fix by cherry-picking from develop.

**Comment by e3rd** [comment]
Amazing, thanks!
