### ISSUE TITLE
Links not updated when renaming/moving page

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1852]
**Describe the bug**
When I move a page to a different sub section using "Rename or Move Page", I am asked whether to update the links to that page. However, even when ticking that box, after the moving, the links are not updated and still point to the old location. There are no links to the new location.

**To Reproduce**
1. Go to a page
2. Click on 'Rename or Move Page'
3. Add nee location and tick box to update links

**Expected behavior**
I expect that all links to the page are updated to point to the new location of the page.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/2971539/148371637-3eb7d393-1480-46c8-8453-8d6bafcdfc78.png)
Moving the page:
![image](https://user-images.githubusercontent.com/2971539/148371709-89e07d70-eb58-4151-8f48-d4c3957c4615.png)
After:
![image](https://user-images.githubusercontent.com/2971539/148371779-bb15c926-84c2-4778-9464-d5104d5ecfb1.png)

**Environment (please complete the following information):**
 - Version 0.74.3 (but also happens with 0.73.5)
 - OS: Windows 10 (bit also happens on MacOS)
 - Language: English

**Additional context**
There is a related error in the debug log:
```
DEBUG: Updating page Journal:2018:05:28 to move link from Projects:StressNF to Reference:StressNF
Traceback (most recent call last):
  File "build/venv/lib/python3.9/site-packages/zim/notebook/page.py", line 155, in makeValidPageName
  File "build/venv/lib/python3.9/site-packages/zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/venv/lib/python3.9/site-packages/zim/notebook/operations.py", line 243, in <lambda>
  File "build/venv/lib/python3.9/site-packages/zim/notebook/operations.py", line 270, in __iter__
  File "build/venv/lib/python3.9/site-packages/zim/notebook/notebook.py", line 575, in move_page_iter
  File "build/venv/lib/python3.9/site-packages/zim/notebook/notebook.py", line 725, in _update_links_to_moved_page
  File "build/venv/lib/python3.9/site-packages/zim/notebook/notebook.py", line 785, in _move_links_in_page
  File "build/venv/lib/python3.9/site-packages/zim/formats/__init__.py", line 668, in replace
  File "build/venv/lib/python3.9/site-packages/zim/formats/__init__.py", line 685, in _replace
  File "build/venv/lib/python3.9/site-packages/zim/formats/__init__.py", line 685, in _replace
  File "build/venv/lib/python3.9/site-packages/zim/formats/__init__.py", line 685, in _replace
  [Previous line repeated 1 more time]
  File "build/venv/lib/python3.9/site-packages/zim/formats/__init__.py", line 679, in _replace
  File "build/venv/lib/python3.9/site-packages/zim/notebook/notebook.py", line 755, in replacefunc
  File "build/venv/lib/python3.9/site-packages/zim/notebook/page.py", line 360, in new_from_wiki_link
  File "build/venv/lib/python3.9/site-packages/zim/notebook/page.py", line 157, in makeValidPageName
ValueError: Not a valid page name:  (was: :)
```

**Comment by jaap-karssenberg** [comment]
The page "Journal:2018:05:28" may contain a weird or invalid link that
causes a bug in the algorithm. Could you check that page and share more
details on the links in that page? Having those details will help to
reproduce the bug.

**Comment by fladd** [comment]
Ah, thanks. There where two links on that page. Not sure what was unusual about them though. I think both had a ":" in front (i.e. :Projects:StressNF). But after I deleted them and inserted them again, it works now!
