### ISSUE TITLE
Gtk errors when running headless and exporting

### ISSUE THREAD

**Issue by hawson** [zim-desktop-wiki/zim-desktop-wiki#1915]
When running headless and exporting an notebook, many Gtk errors are thrown

```
$ echo $DISPLAY
:0.0
$ zim --export -V -r --format markdown -O -o /dev/shm/foo  ./Notes/
INFO: This is zim 0.74.2
INFO: No VCS detected
INFO: Loading template from: /usr/share/zim/templates/markdown/Default.markdown
[...]
```
Appears to work okay.

However, if you unset DISPLAY (_i.e._ headless):
```
$ DISPLAY= zim  --export -V -r --format markdown -O -o /dev/shm/foo  ./Notes/

(zim:3098076): Gdk-CRITICAL **: 13:14:36.615: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
(zim:3098076): Gdk-CRITICAL **: 13:14:36.615: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed
(zim:3098076): Gdk-CRITICAL **: 13:14:36.615: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
(zim:3098076): Gtk-CRITICAL **: 13:14:36.615: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed
(zim:3098076): Gtk-CRITICAL **: 13:14:36.653: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

ERROR: Exception while loading plugin: pageindex
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/zim/plugins/__init__.py", line 405, in load_plugins_from_preferences
    self.load_plugin(name)
  File "/usr/lib/python3.9/site-packages/zim/plugins/__init__.py", line 513, in load_plugin
    klass = self.get_plugin_class(name)
  File "/usr/lib/python3.9/site-packages/zim/plugins/__init__.py", line 460, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3.9/site-packages/zim/utils.py", line 36, in get_module
    mod = __import__(name)
  File "/usr/lib/python3.9/site-packages/zim/plugins/pageindex/__init__.py", line 22, in <module>
    from zim.gui.notebookview import NotebookViewExtension
  File "/usr/lib/python3.9/site-packages/zim/gui/__init__.py", line 23, in <module>
    set_icon_search_path()
  File "/usr/lib/python3.9/site-packages/zim/gui/__init__.py", line 21, in set_icon_search_path
    icon_theme.append_search_path(dir.subdir('icons').path)
AttributeError: 'NoneType' object has no attribute 'append_search_path'

[ ... errors and traceback repeats several more times for the plugins listed below ... ]

INFO: This is zim 0.74.2
INFO: Loading template from: /usr/share/zim/templates/markdown/Default.markdown

[...export continues...]
```
An error and backtrace is produced for these plugins:
```
ERROR: Exception while loading plugin: pageindex
ERROR: Exception while loading plugin: insertsymbol
ERROR: Exception while loading plugin: versioncontrol
ERROR: Exception while loading plugin: spell
ERROR: Exception while loading plugin: trayicon
ERROR: Exception while loading plugin: journal
ERROR: Exception while loading plugin: diagrameditor
ERROR: Exception while loading plugin: sourceview
```

Version 0.74.2, as indicated, running on Python 3.9.9.

This is similar to, but different from #579

**Comment by introt** [comment]
As long as the export completes, gtk errors can safely be ignored
