### ISSUE TITLE
[develop] reverseTopLevelLists errors on large indent changes (breaking link updates)

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1950]
**Describe the bug**
Updating links to moved page fails silently due to some token parsing error.

**To Reproduce**
See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1950#issuecomment-1048891711 for a more minimal example
1. Put the following into a page called `:Test`

```
====== Test ======
[[:Move me|Move me]]

* foo
{{pasted_image.png}}
		* foobar
	* buzz
```

2. Use "Rename or Move page..." to move "Move me" to "Moved"
3. Nothing happens

**Expected behavior**
The link in `:Test` would get updated

**Environment (please complete the following information):**
 - Version 524907ff2916f9ec52373be4cf997e93b1ff4e18
 - OS: linux
 - Language: en_US.UTF-8

**Additional context**

See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1950#issuecomment-1048899446 for a test case

Patch:
```

diff --git a/zim/tokenparser.py b/zim/tokenparser.py
index be8303e8..461f5c89 100644
--- a/zim/tokenparser.py
+++ b/zim/tokenparser.py
@@ -20,6 +20,9 @@
 from zim.parser import Builder
 from zim.formats import NUMBEREDLIST, BULLETLIST, LISTITEM, PARAGRAPH, ANCHOR
 
+import logging
+logger = logging.getLogger()
+
 TEXT = 'T'
 END = '/'
 
@@ -237,6 +240,7 @@ def _changeList(tokeniter):
 
 
 def reverseTopLevelLists(tokens):
+       logger.critical("tokens: %s", tokens)
        # Undo effect of topLevelLists()
        #
        # <br><ul>...</ul><br> --> <p><ul>...</ul></p>
@@ -246,11 +250,14 @@ def reverseTopLevelLists(tokens):
        #
 
        def isbr(token):
+               logger.critical("isbr(token): %s", token)
                return token[0] == TEXT and token[1].isspace() and '\n' in token[1]
 
        tokeniter = iter(tokens)
        newtokens = []
        for t in tokeniter:
+               logger.critical("token: %s", t)
+
                if t[0] in (NUMBEREDLIST, BULLETLIST):
                        if newtokens and newtokens[-1] == (END, PARAGRAPH):
                                newtokens.pop()
@@ -261,6 +268,7 @@ def reverseTopLevelLists(tokens):
                        newtokens.extend(_reverseChangeList(tokeniter))
 
                        nexttoken = next(tokeniter)
+                       logger.critical("nexttoken: %s", nexttoken)
                        if nexttoken[0] in (BULLETLIST, NUMBEREDLIST) \
                        or nexttoken[0] == END and nexttoken[1] in (BULLETLIST, NUMBEREDLIST):
                                raise AssertionError
```

Logs with patch:

```
DEBUG: Action: move_page
DEBUG: Opening dialog "Rename or Move Page"
DEBUG: Dialog response OK
DEBUG: Opening ProgressDialog: Updating Links
DEBUG: Move page Move me to Moved
DEBUG: Updating page Test to move link from Move me to Moved
CRITICAL: tokens: [('zim-tree', {}), ('h', {'level': 1}), ('T', 'Test\n'), ('/', 'h'), ('p', {}), ('link', {'href': ':Moved'}), ('T', 'Moved'), ('/', 'link'), ('T', '\n'), ('/', 'p'), ('T', '\n'), ('ul', {}), ('li', {'bullet': '*'}), ('T', 'foo\n'), ('/', 'li'), ('/', 'ul'), ('p', None), ('img', {'src': 'pasted_image.png'}), ('/', 'img'), ('T', '\n'), ('/', 'p'), ('ul', {'indent': 2}), ('li', {'bullet': '*'}), ('T', 'foobar\n'), ('/', 'li'), ('/', 'ul'), ('ul', {'indent': 1}), ('li', {'bullet': '*'}), ('T', 'buzz\n'), ('/', 'li'), ('/', 'ul'), ('/', 'zim-tree')]
CRITICAL: token: ('zim-tree', {})
CRITICAL: token: ('h', {'level': 1})
CRITICAL: token: ('T', 'Test\n')
CRITICAL: token: ('/', 'h')
CRITICAL: token: ('p', {})
CRITICAL: token: ('link', {'href': ':Moved'})
CRITICAL: token: ('T', 'Moved')
CRITICAL: token: ('/', 'link')
CRITICAL: token: ('T', '\n')
CRITICAL: token: ('/', 'p')
CRITICAL: token: ('T', '\n')
CRITICAL: token: ('ul', {})
CRITICAL: nexttoken: ('p', None)
CRITICAL: token: ('img', {'src': 'pasted_image.png'})
CRITICAL: token: ('/', 'img')
CRITICAL: token: ('T', '\n')
CRITICAL: token: ('/', 'p')
CRITICAL: token: ('ul', {'indent': 2})
CRITICAL: nexttoken: ('ul', {'indent': 1})
Traceback (most recent call last):
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/operations.py", line 243, in <lambda>
    GObject.idle_add(lambda: next(my_iter, False), priority=GObject.PRIORITY_LOW)
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/operations.py", line 270, in __iter__
    progress = next(self._do_work)
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/notebook.py", line 569, in move_page_iter
    for p in self._update_links_to_moved_page(path, newpath):
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/notebook.py", line 717, in _update_links_to_moved_page
    self._move_links_in_page(link.source, oldroot, newroot)
  File "/home/introt/repos/zim-desktop-wiki/zim/notebook/notebook.py", line 777, in _move_links_in_page
    newtree = tree.substitute_elements((zim.formats.LINK,), replacefunc)
  File "/home/introt/repos/zim-desktop-wiki/zim/formats/__init__.py", line 668, in substitute_elements
    return ParseTree.new_from_tokens(tokens)
  File "/home/introt/repos/zim-desktop-wiki/zim/formats/__init__.py", line 323, in new_from_tokens
    parser.parse(tokens)
  File "/home/introt/repos/zim-desktop-wiki/zim/tokenparser.py", line 157, in parse
    for t in reverseTopLevelLists(tokens):
  File "/home/introt/repos/zim-desktop-wiki/zim/tokenparser.py", line 275, in reverseTopLevelLists
    raise AssertionError
AssertionError
DEBUG: Closed dialog "Rename or Move Page"
```

**Comment by introt** [comment]
I have no idea how Zim's token stuff works, but we might want to test for this edge case in html exports as well (do they get the correct amount of opening/closing tags?)

**Comment by introt** [comment]
This allows us to build a test:

```
diff --git a/tests/data/formats/wiki.txt b/tests/data/formats/wiki.txt
index e8b0bc53..076b2e53 100644
--- a/tests/data/formats/wiki.txt
+++ b/tests/data/formats/wiki.txt
@@ -78,6 +78,12 @@ Indented list:
                * item b
        * item 4
 
+List with large indentation changes:
+* item 1
+               * item 1 a
+* item 2
+                               * item 2   a
+* item 3
 
 TODO list:
 [ ] foo
```
