### ISSUE TITLE
Unable to save zim notebook when it is located in an SMB shared drive aftrer upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by j4bbyj03** [zim-desktop-wiki/zim-desktop-wiki#2098]
Hi,

I have my entire notebook in an SMB share.  Prior to my upgrade to Ubuntu 22.04, I could open and save my notebooks.  After upgrading to 22.04 I could still open *.zim files but could not save changes to any of my notebooks. It is throwing this error:

`Could not save page: ...`
`[Errno 5 Input/ouptpu error: 'run/user/100/fgvfs/smb-share:server=...`

![image](https://user-images.githubusercontent.com/108677146/177168518-040783c4-d781-4179-be0b-c836bec5f406.png)

It seems to be an issue with zim notebook because:
- I was able to open, create, edit and save a text file using a different text editor
- I reinstalled zim using  `sudo apt-get --purge remove` command then reinstalled it

I am using Samba version 4.15.5-Ubuntu and my computer is using Linux kernel 5.15.0-40-generic

Thank you :-)

**Comment by jaap-karssenberg** [comment]
Can you add a bit more information on how you setup the notebooks? How does
the file path look like ? Can you share debug output ?

Thanks,

Jaap

**Comment by j4bbyj03** [comment]
Hi Jaap,

My apologies for the late reply.  I was affected by that Rogers internet outage over the weekend.

Here are some details to my set up:
- My notebook is on a shared drive
- I mounted it with both read and write access
- My prior linux version that worked is 21.10
- My current linux version is an ubuntu 22.04 with 5.15.0-40-generic #43-Ubuntu kernel

I am no linux expert please let me know if need more info aside from the ones I typed above.  As for the other info you had asked:

- The source path is: 
`/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt`

- The debug output looks like this:
`DEBUG: Recieved remote call: ('/home/ajoviedo', '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/notebook.zim')
DEBUG: Loading config from: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/notebook.zim
DEBUG: Connecting to database file: /home/ajoviedo/.cache/zim/notebook-run_user_1000_gvfs_smb-share:server=anorlondo.local,share=ajoviedo_Zim_Notebooks/index.db
DEBUG: Loading config from: /home/ajoviedo/.cache/zim/notebook-run_user_1000_gvfs_smb-share:server=anorlondo.local,share=ajoviedo_Zim_Notebooks/state.conf
DEBUG: New extendable: <Notebook: notebook>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookExtension'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: VCS detected: git - /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks
DEBUG: Autosave interval: 15 - use threads: True
INFO: Page changed on disk: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
INFO: Open page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions (01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions)
DEBUG: New extendable: <notebookview.NotebookView object at 0x7fa34edaa480 (zim+gui+notebookview+NotebookView at 0x55bfdb9253f0)>
DEBUG: Load extension: <class 'zim.plugins.arithmetic.ArithmeticPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
ERROR: Error while setting up file monitor
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/newfs/helpers.py", line 119, in _setup_signal
    self._gio_file_monitor = file.monitor(0, None)
gi.repository.GLib.GError: g-io-error-quark: Operation not supported (15)
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
DEBUG: Load extension: <class 'zim.plugins.inlinecalculator.InlineCalculatorPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.screenshot.ScreenshotPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7fa34ed0f340 (zim+gui+mainwindow+MainWindow at 0x55bfdc019760)>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.trayicon.TrayIconMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
DEBUG: Accelmap: /home/ajoviedo/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: Accelmap: /home/ajoviedo/.config/zim/accelmap
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal
DEBUG: Index file: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects.txt
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/01_-_Technical/03_-_Operational
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/02_-_AppSpider
DEBUG: Index folder: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/02_-_AppSpider/01_-_Weekly_Review
DEBUG: Index file: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/02_-_AppSpider/02_-_Scheduling.txt
DEBUG: Index file: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/02_-_AppSpider/01_-_Weekly_Review/2022.txt
DEBUG: BackgroundCheck started
DEBUG: Store page in background: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
ERROR: Error in background save
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 505, in _store_page_async_thread_main
    page._store_tree(parsetree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt'
DEBUG: Saving page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
DEBUG: Store page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
ERROR: Failed to save page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt'
DEBUG: Running SavePageErrorDialog
DEBUG: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt'
ERROR: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~
DEBUG: BackgroundCheck finished
DEBUG: Saving page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
DEBUG: Store page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
ERROR: Failed to save page: 01-Work:Paymentus:06 - Tools:03 - Nessus:Exceptions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt'
DEBUG: Running SavePageErrorDialog
DEBUG: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt'
ERROR: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/01-Work/Paymentus/06_-_Tools/03_-_Nessus/Exceptions.txt.zim-new~
INFO: Open page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation (00-Personal:00 - Projects:00 - Home Improvement:Home Automation)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: save_page
DEBUG: Saving page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
DEBUG: Store page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
ERROR: Failed to save page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt'
DEBUG: Running SavePageErrorDialog
DEBUG: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt'
ERROR: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~
DEBUG: Store page in background: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
ERROR: Error in background save
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 505, in _store_page_async_thread_main
    page._store_tree(parsetree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt'
DEBUG: Last auto-save resulted in error, re-try in foreground
DEBUG: Saving page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
DEBUG: Store page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
ERROR: Failed to save page: 00-Personal:00 - Projects:00 - Home Improvement:Home Automation
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt'
DEBUG: Running SavePageErrorDialog
DEBUG: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py", line 5464, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 372, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 477, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 513, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 535, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 725, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 739, in _write_with_etag
    func(content)
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 394, in writelines
    with AtomicWriteContext(self, newline=newline) as fh:
  File "/usr/lib/python3/dist-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Input/output error: '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~' -> '/run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt'
ERROR: Input/output error: /run/user/1000/gvfs/smb-share:server=anorlondo.local,share=ajoviedo/Zim_Notebooks/00-Personal/00_-_Projects/00_-_Home_Improvement/Home_Automation.txt.zim-new~

(zim:18498): Gtk-WARNING **: 09:21:45.422: GtkTextView - did not receive focus-out-event. If you
connect a handler to this signal, it must return
FALSE so the text view gets the event as well
WARNING: /usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py:5595: Warning: Source ID 5324 was not found when attempting to remove it
  GObject.source_remove(id)`

Thank you :-)

**Comment by stardustasteroidnix** [comment]
I have a similar problem: My ZIM-notebook is also located on SMB-share. If I want to open this, I get an input/output-error.
With LinuxMint 20.3 (Ubuntu 20.04) everything is ok (read and write without error), with LinuxMint 21 (Ubuntu 22.04) access is not possible.
I use ZIM version 0.74.3 via flatpak.

`Gtk-Message: 17:39:07.301: Failed to load module "appmenu-gtk-module"
Gtk-Message: 17:39:07.301: Failed to load module "canberra-gtk-module"
DEBUG: Loading config from: <ConfigFile: /home/username/.var/app/org.zim_wiki.Zim/config/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x7feb3626e3a0>
DEBUG: Loading plugin: pageindex
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: toolbar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
INFO: This is zim 0.74.3
DEBUG: Python version is sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/username/.var/app/org.zim_wiki.Zim/data
DEBUG: Set XDG_DATA_DIRS to [<Dir: /app/share>, <Dir: /usr/share>, <Dir: /usr/share/runtime/share>, <Dir: /run/host/user-share>, <Dir: /run/host/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/username/.var/app/org.zim_wiki.Zim/config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /app/etc/xdg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/username/.var/app/org.zim_wiki.Zim/cache
DEBUG: Connecting to /run/user/1000/zim-0.74.3-d6f0fbfe
DEBUG: Got error in dispatch: No such file or directory
WARNING: Could not find all icon sizes for the application icon
DEBUG: Starting primary process
DEBUG: Start listening on: /run/user/1000/zim-0.74.3-d6f0fbfe
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7feb316b0160>
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7feb316785b0>
DEBUG: First time usage - prompt for notebook folder
DEBUG: Opening dialog "Add Notebook"
DEBUG: Opening dialog "Add Notebook"
DEBUG: Opening dialog "Select Folder"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Select Folder"
DEBUG: Loading config from: /run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=10.10.10.10,share=daten,user=smbuser/WiKi/notebook.zim
DEBUG: Dialog response OK
DEBUG: Closed dialog "Add Notebook"
DEBUG: Loading config from: /run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=10.10.10.10,share=daten,user=smbuser/WiKi/notebook.zim
DEBUG: Exception in main()
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 936, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 707, in run
    self._run_cmd(cmd, args) # test seam
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 738, in _run_cmd
    self._run_main_loop(cmd)
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 780, in _run_main_loop
    w = cmd.run()
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 268, in run
    notebook, page = self.build_notebook()
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 234, in build_notebook
    notebookinfo = prompt_notebook_list()
  File "/app/lib/python3.9/site-packages/zim/main/__init__.py", line 219, in prompt_notebook_list
    return zim.gui.notebookdialog.prompt_notebook()
  File "/app/lib/python3.9/site-packages/zim/gui/notebookdialog.py", line 63, in prompt_notebook
    init_notebook(dir, name=fields['name'])
  File "/app/lib/python3.9/site-packages/zim/notebook/__init__.py", line 187, in init_notebook
    config.write()
  File "/app/lib/python3.9/site-packages/zim/config/dicts.py", line 812, in write
    self.file.writelines(self.dump())
  File "/app/lib/python3.9/site-packages/zim/fs.py", line 1219, in writelines
    fh.writelines(lines)
  File "/app/lib/python3.9/site-packages/zim/newfs/local.py", line 305, in __exit__
    _replace_file(self.tmppath, self.path)
OSError: [Errno 5] Eingabe-/Ausgabefehler: '/run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=10.10.10.10,share=daten,user=smbuser/WiKi/notebook.zim.zim-new~' -> '/run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=10.10.10.10,share=daten,user=smbuser/WiKi/notebook.zim'
ERROR: Eingabe-/Ausgabefehler: /run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=10.10.10.10,share=daten,user=smbuser/WiKi/notebook.zim.zim-new~
DEBUG: Running ErrorDialog
`

**Comment by introt** [comment]
Both 20.04 and 21.10 ship Samba 4.13.17, while 22.04 has version 4.15.5. Looking at the changelog, I'd guess that the issue is due to changes introduced by the switch to [the new VFS](https://wiki.samba.org/index.php/The_New_VFS).

As a workaround, you may need to sync between a local copy and the one on the share for the time being.
