### ISSUE TITLE
on export: TypeError: 'PageProxy' object is not subscriptable

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2174]
**Describe the bug**

Fails to export.

**To Reproduce**

```
> /opt/homebrew/bin/zim --export --recursive --overwrite --output=/Users/reagle/joseph/zwiki --format=html --template=~/.local/share/zim/templates/html/codex-default.html /Users/reagle/joseph/zim --format=html --index-page index
...
exporting /Users/reagle/joseph/plan/joseph-nora/
results_out =
results_sdterr = ERROR: Exception exporting page: Home:Archive:2014:Summer:Vietnam
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/zim/0.75.0/libexec/lib/python3.10/site-packages/zim/templates/expression.py", line 120, in __call__
    value = value[p]
TypeError: 'PageProxy' object is not subscriptable

```

**Environment (please complete the following information):**

- zim 0.75.0
- OS: macOS 12.6 21G115 arm64
- Language: English

**Comment by jaap-karssenberg** [comment]
Can you include the template; would need to know what template expression
triggers this error.

Regards,

Jaap

**Comment by reagle** [comment]
This was with the zim from homebrew, which [has ongoing issues](https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1749). I'm going to continue waiting for @dehesselle's package and I'll follow up once I try that.

**Comment by reagle** [comment]
I jus t installed @dehesselle's package and get the same.

```
ERROR: Exception exporting page: Teaching:Exercises
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/expression.py", line 120, in __call__
    value = value[p]
TypeError: 'PageProxy' object is not subscriptable
```

The template is attached (with txt extension since Github doesn't accept HTML.)

[codex-default.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/9746106/codex-default.txt)

**Comment by reagle** [comment]
Because of this issue I was continuing to use `Zim-0.74.3_120_arm.dmg`. Unfortunately, after upgrading to Ventura, that binary would crash, so I looked around and saw `Zim-0.75.1+227_arm64.dmg` was available for Ventura. I've installed that, but it has this particular error and now I'm unable to export my Zim to my webpages. I'm stuck!

**Comment by dehesselle** [comment]
@reagle A working 0.74.3 would get you unstuck?

After the release 0.75.1+227 a serious issue with Ventura was discovered (UI not responding to mouse events) which I cannot fix.

**Comment by reagle** [comment]
I can confirm I have #2219 too, but it's not a big deal since I prefer the the keyboard anyway. I suppose a 0.7.43 would get me unstuck as long as it worked and could export. I don't know why it didn't work on Ventura? I'd be just as happy to stay with 0.7.51 if I could get #2174 addressed, which sounds like maybe there's a problem with my template? I did share it above, but @jaap-karssenberg didn't respond.

**Comment by dehesselle** [comment]
The only thing I can do is build a working 0.74.3 for you.

The crash on Ventura has nothing to do with Zim itself, but Ventura introduced a change that broke my launcher. It just happened that I fixed the crash while I was already on 0.75.x and I don't rebuild older versions.

**Comment by reagle** [comment]
Thank you. If it's not too much trouble then: yes! :)

**Comment by dehesselle** [comment]
These are not release builds, so you might have to `xattr -r -d com.apple.quarantine Zim.app`.
https://gitlab.com/dehesselle/zim_macos/-/jobs/3307151102/artifacts/raw/Zim_0.74.3+230_arm64.dmg
https://gitlab.com/dehesselle/zim_macos/-/jobs/3307151098/artifacts/raw/Zim_0.74.3+230_x86_64.dmg

**Comment by reagle** [comment]
Thanks! I did `xattr -r -d com.apple.quarantine /Applications/Zim.app` and the GUI works as does the commandline export.

**Comment by jaap-karssenberg** [comment]
@reagle afraid I can't reproduce the issue with the template provided and my own test notebook. What is worse, from code inspection I can't understand how this error could occur. The line referred to in the message is explicitly wrapped in a `try .. except ..` block to catch this error type.

See https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/e4b04df4737cde00d0c159b1007361204fa7856c/zim/templates/expression.py#L120

Anyone a clue how this could happen or how to reproduce ?

**Comment by reagle** [comment]
I'm running Ventura (macOS 13.0.1 22A400 arm64) now, so I grabbed the 0.75.0 dmg and ran it from `/Applications` (rather the homebrew version in `/opt`) and yields a similar result. Note the "During handling of the above exception, another exception occurred":

```
❯ /Applications/Zim.app/Contents/MacOS/Zim --export --recursive --overwrite --output=/Users/reagle/joseph/zwiki --format=html --template=~/.local/share/zim/templates/html/codex-default.html /Users/reagle/joseph/zim --format=html --index-page index
ERROR: Exception exporting page: Archives:2013
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/expression.py", line 120, in __call__
    value = value[p]
TypeError: 'PageProxy' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/export/template.py", line 427, in body
    head, body = self._split_head()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/export/template.py", line 453, in _split_head
    head, tree = split_heading_from_parsetree(self._tree, keep_head_token=False)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/formats/__init__.py", line 698, in split_heading_from_parsetree
    return (ParseTree.new_from_tokens(heading), ParseTree.new_from_tokens(body))
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/formats/__init__.py", line 317, in new_from_tokens
    assert tokens
AssertionError
ERROR: Exception in signal handler for process on <zim.templates.Template object at 0x108b1e7a0>
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/expression.py", line 120, in __call__
    value = value[p]
TypeError: 'PageProxy' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/signals.py", line 367, in emit
    r = handler(self, *args)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/__init__.py", line 202, in do_process
    processor.process(output, context)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/processor.py", line 82, in process
    self.__call__(output, self.main, context)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/processor.py", line 131, in __call__
    self._loop(output, element, context)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/processor.py", line 172, in _loop
    self.__call__(output, element, context) # recurs
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/processor.py", line 112, in __call__
    value = expr(context)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/expression.py", line 123, in __call__
    value = getattr(value, p)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/export/template.py", line 427, in body
    head, body = self._split_head()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/export/template.py", line 453, in _split_head
    head, tree = split_heading_from_parsetree(self._tree, keep_head_token=False)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/formats/__init__.py", line 698, in split_heading_from_parsetree
    return (ParseTree.new_from_tokens(heading), ParseTree.new_from_tokens(body))
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/formats/__init__.py", line 317, in new_from_tokens
    assert tokens
AssertionError
ERROR: Exception exporting page: Teaching:Assignments
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/templates/expression.py", line 120, in __call__
    value = value[p]
TypeError: 'PageProxy' object is not subscriptable

During handling of the above exception, another exception occurred:
...
```

**Comment by jaap-karssenberg** [comment]
Thanks for the extended error log, that allowed to find & fix the bug. Please confirm whether the patch below works for you. Regards, Jaap

**Comment by reagle** [comment]
Yes, that works. Thank you!

**Comment by gandrille** [comment]
I had the same issue when generating site with zim 0.75.1 
Commit https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/2d2970fc136eb6baf00d62e8d7ad1e024e54dcab fixed it perfectly.
Thanks !
