### ISSUE TITLE
Fwd: [abrt] Zim: _move_file_and_folder(): notebook.py:599:_move_file_and_folder:zim.notebook.notebook.PageExistsError: <exception str() failed>

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#2382]
https://bugzilla.redhat.com/show_bug.cgi?id=2213835

Version-Release number of selected component:
Zim-0.75.1-2.fc38

Additional info:
reporter:       libreport-2.17.10
kernel:         6.3.5-200.fc38.x86_64
cmdline:        /usr/bin/python3 /usr/bin/zim
cgroup:         0::/user.slice/user-1000.slice/user/app.slice/app-gnome-zim-269451.scope
uid:            1000
reason:         notebook.py:599:_move_file_and_folder:zim.notebook.notebook.PageExistsError: <exception str() failed>
executable:     /usr/bin/zim
type:           Python3
package:        Zim-0.75.1-2.fc38
runlevel:       N 5
exception_type: zim.notebook.notebook.PageExistsError
crash_function: _move_file_and_folder
interpreter:    python3-3.11.3-2.fc38.x86_64

Truncated backtrace:
notebook.py:599:_move_file_and_folder:zim.notebook.notebook.PageExistsError: <exception str() failed>

Traceback (most recent call last):
```
  File "/usr/lib/python3.11/site-packages/zim/notebook/operations.py", line 243, in <lambda>
    GObject.idle_add(lambda: next(my_iter, False), priority=GObject.PRIORITY_LOW)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/zim/notebook/operations.py", line 270, in __iter__
    progress = next(self._do_work)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/zim/notebook/notebook.py", line 559, in move_page_iter
    self._move_file_and_folder(path, newpath)
  File "/usr/lib/python3.11/site-packages/zim/notebook/notebook.py", line 599, in _move_file_and_folder
    raise PageExistsError(newpath)
zim.notebook.notebook.PageExistsError: <exception str() failed>
```

Local variables in innermost frame:
self: <Notebook: Notes>
path: <PageIndexRecord: kubernetes>
newpath: <Path: FOSS:kubernetes>
file: <LocalFile: /home/renich/Documents/Notebooks/Notes/kubernetes.txt>
folder: <LocalFolder: /home/renich/Documents/Notebooks/Notes/kubernetes>
newfile: <LocalFile: /home/renich/Documents/Notebooks/Notes/FOSS/kubernetes.txt>
newfolder: <LocalFolder: /home/renich/Documents/Notebooks/Notes/FOSS/kubernetes>

**Comment by oturpe** [comment]
I have started trying to fix this.
The issue can be reproduced like this:

**Comment by oturpe** [comment]
I have started trying to fix this.
The issue can be reproduced like this:

1. Create page called "A"
2. Create page called "B" with subpage called "A"
3. Attempt to move page "A" under "B"

Thus, the raised exception seems correct.
It is just that it should be caught and shown to user,
rather than letting a crash happen and print to the debug log only.

Unfortunately, I have no previous experience of this part of the Zim code base or the GTK event loop.
Any pointer on what is the correct way to handle exceptions in this context would be appreciated.
Doing about one hour of searches in the code base did not reveal any place that I could just copy , paste and modify.

**Comment by oturpe** [comment]
First reported for Fedora as [rhbz#2213835](https://bugzilla.redhat.com/show_bug.cgi?id=2213835).

**Comment by oturpe** [comment]
Ok, I have determined that the exception is caught, but re-raised here:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/notebook/operations.py#L279
Sending it out of application and leading to the crash that ABRT wants to report.
(I have not investigated if there is some way to configure GTK to do something special here.)

And also that I can check content of `op.exception` after this line:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/gui/uiactions.py#L658

My current questions are:

1. What would be the best way to stop the exception from propagating until it results in a crash?
Make the exception handler configurable, so that in this case, the PageExistsError can be caught and handled properly?
2. After that is done, how to show the error message to the user?

**Comment by introt** [comment]
One way is for it to be re-raised as an `zim.Error` to be caught and shown to the user in the "Looks like you've found a bug" dialog along with traceback. https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/errors.py#L103

There're also `zim.errors.exception_handler` and `show_error` which can be seen here and are perhaps more appropriate: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1794#issuecomment-992194894

**Comment by oturpe** [comment]
It turns out that the error already *is* inherited from `zim.Error`, still user was not shown anything.
The actions started from `Dialog` instances have some special behavior here.
#2482 makes the error visible to user.
If that pull request is merged, everything is fine here from Zim's perspective.

However, in Fedora, an ABRT crash report is still triggered.
I will look at that next.
Perhaps there is a different way of handling exceptions from `Dialog` that works for Zim and will not trigger ABRT.
