### ISSUE TITLE
[Zim for macOS] Operation Timed Out

### ISSUE THREAD

**Issue by supermanoy** [zim-desktop-wiki/zim-desktop-wiki#2433]
I am using macOS Ventura 13.4.1 (c), and installed this one: https://gitlab.com/api/v4/projects/30529415/packages/generic/zim_macos/0.75.2%2B264/Zim-0.75.2+264_arm64.dmg, when I open the app, there's a small popup that says, "Operation Timed Out"

1. Open Zim
2. An error will popup
3. Zim wont start

Installer works fine, I am using Apple M1, however, It won't start. It was working fine last week. Tried using old installers that supports Ventura but no luck, same error message.

Screenshot 
<img width="208" alt="Screenshot 2023-07-26 at 9 45 12 AM" src="https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/123355853/97948d03-06ec-4b71-ac2c-d0e69b7135d2">

 - OS: macOS Ventura 13.4.1 (c)
 - Language: Englis

**Comment by dehesselle** [comment]
What output do you get when you run Zim from the terminal as follows:
```bash
/Applications/Zim.app/Contents/MacOS/Zim -D
```

**Comment by supermanoy** [comment]
Hello,

Sorry for late revert, this is what I get from running  Zim from terminal:

MacBook-Pro MacOS % Zim -D
Traceback (most recent call last):
  File "/opt/homebrew/bin/Zim", line 113, in main
    import zim
ModuleNotFoundError: No module named 'zim'
ERROR: Could not find python module files in path:
/opt/homebrew/bin /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python311.zip /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11 /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload /Users/ronaldfajardo/Library/Python/3.11/lib/python/site-packages /opt/homebrew/lib/python3.11/site-packages /opt/homebrew/lib/python3.11/site-packages/nps_sdk-1.3.1-py3.11.egg

It was working fine before.

**Comment by dehesselle** [comment]
In your first post you say you are using the official app but the output suggests you are using a Zim installation via Homebrew. You'll have to ask Homebrew, we don't offer support for that.

**Comment by supermanoy** [comment]
I installed on brew, and the one from brew was working fine if ran using the terminal, I removed the brew installation and the error is still the same, when I ran "Zim -D", it now displays, "command not found". This is after uninstalling the brew version

**Comment by supermanoy** [comment]
This is how it looks like, i tried running "./Zim -D" instead

<user>@<user>-MacBook-Pro MacOS % ls
Zim
<user>@<user>-MacBook-Pro MacOS % Zim -D
zsh: command not found: Zim
<user>@<user>-MacBook-Pro MacOS % ./Zim -D
DEBUG: Can not import 'xdg.Mime' - falling back to 'mimetypes'
INFO: Can not import 'xdg.Mime' - falling back to 'mimetypes'
DEBUG: Loading config from: <ConfigFile: /Users/<user>/Library/Application Support/org.zim-wiki.Zim/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x10556c790>
DEBUG: Loading plugin: pageindex
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: toolbar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: versioncontrol
DEBUG: Loading plugin: osx_menubar
INFO: This is zim 0.75.2
DEBUG: Python version is sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /Users/<user>/Library/Application Support/org.zim-wiki.Zim/share
DEBUG: Set XDG_DATA_DIRS to [<LocalFolder: /Users/<user>/.Trash/Zim.app/Contents/Resources/share>]
DEBUG: Set XDG_CONFIG_HOME to /Users/<user>/Library/Application Support/org.zim-wiki.Zim
DEBUG: Set XDG_CONFIG_DIRS to [<LocalFolder: /Users/<user>/.Trash/Zim.app/Contents/Resources/etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /Users/<user>/Library/Caches/org.zim-wiki.Zim
DEBUG: Connecting to /tmp/zim-0.75.2-9a826f6f
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-0.75.2-9a826f6f
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x1098b6110>
DEBUG: Loading config from: /Users/<user>/Documents/<user>/notebook.zim
DEBUG: Loading config from: /Users/<user>/OneDrive/ZIM <user>/notebook.zim
ERROR: Exception while loading notebook list:
Traceback (most recent call last):
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/info.py", line 253, in __init__
    self.update()
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/info.py", line 428, in update
    changed = info.update() or changed
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/info.py", line 201, in update
    config = NotebookConfig(file)
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/notebook.py", line 44, in __init__
    INIConfigFile.__init__(self, file)
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/config/dicts.py", line 756, in __init__
    self.read()
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/config/dicts.py", line 783, in read
    self.parse(self.file.readlines())
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/newfs/local.py", line 375, in readlines
    return [l.lstrip('\ufeff').replace('\x00', '') for l in fh]
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/newfs/local.py", line 375, in <listcomp>
    return [l.lstrip('\ufeff').replace('\x00', '') for l in fh]
TimeoutError: [Errno 60] Operation timed out
DEBUG: Loading config from: /Users/<user>/OneDrive/ZIM <user>/notebook.zim
DEBUG: Exception in main()
Traceback (most recent call last):
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 764, in _run_cmd
    self._run_main_loop(cmd)
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 806, in _run_main_loop
    w = cmd.run()
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 268, in run
    notebook, pagelink = self.build_notebook()
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 240, in build_notebook
    notebook, uripagelink = build_notebook(notebookinfo) # can raise FileNotFound
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/__init__.py", line 130, in build_notebook
    notebook = Notebook.new_from_dir(folder)
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/notebook.py", line 246, in new_from_dir
    config = NotebookConfig(dir.file('notebook.zim'))
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/notebook.py", line 44, in __init__
    INIConfigFile.__init__(self, file)
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/config/dicts.py", line 756, in __init__
    self.read()
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/config/dicts.py", line 783, in read
    self.parse(self.file.readlines())
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/newfs/local.py", line 375, in readlines
    return [l.lstrip('\ufeff').replace('\x00', '') for l in fh]
  File "/Users/<user>/.Trash/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/newfs/local.py", line 375, in <listcomp>
    return [l.lstrip('\ufeff').replace('\x00', '') for l in fh]
TimeoutError: [Errno 60] Operation timed out
ERROR: Operation timed out
DEBUG: Running ErrorDialog
<user>@<user>-MacBook-Pro MacOS %

**Comment by dehesselle** [comment]
There have been reports of problems with cloud storage like OneDrive before. For testing purposes, move your Zim notebooks off OneDrive to some local (non-cloud storage) folder.

If you can't get Zim to start because it keeps trying to open the notebooks from OneDrive, nuke the settings directory in `~/Library/Application Support/org.zim-wiki.Zim`.

**Comment by supermanoy** [comment]
Thank you @dehesselle! It is now working fine like before.
I am just curious what is causing the problem, I am saving my notebook with OnDrive since the day I installed Zim.

Anyway, issue has been fixed. Thanks again!
