### ISSUE TITLE
Tag filter doesn't switch to correct page when page highlighted

### ISSUE THREAD

**Issue by jungle-boogie** [zim-desktop-wiki/zim-desktop-wiki#2434]
Hello,

With the tag cloud, you can see all your tags and the pages where they appear.
If you click a tag, it will show you the appropriate page.

However, if you click on the page to display the tag, the page will not be displayed.

**To Reproduce**
1. Open tag cloud
2. Click a tag
3. Click a page a tag appears on
4. Notice page where the tag appears is not displayed

**Expected behavior**
I would expect clicking on the page I've filtered down to display the page.

**Screenshots**
If this screenshot you will notice I have the desk tag filtered, then the plugins:Task List page highlighted, but the displayed page is a ToDo Lists page.

![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1111743/0a45cdf4-1c32-4993-adfe-f2815b239b87)

**Environment (please complete the following information):**
- `zim-wiki` version 0.75.2
- Platform: Windows 10

**Comment by jungle-boogie** [comment]
If I right-click on `Plugins:Task List` and select open in new window, then the appropriate page will be opened.

**Comment by introt** [comment]
Confirmed. Debug log:

```
Traceback (most recent call last):
  File "/home/introt/repos/zim-desktop-wiki/zim/plugins/pageindex/__init__.py", line 484, in do_row_activated
    self.restore_autoexpanded_path()
  File "/home/introt/repos/zim-desktop-wiki/zim/plugins/pageindex/__init__.py", line 704, in restore_autoexpanded_path
    if not self.get_any_children_expanded(prev_treepath):
  File "/home/introt/repos/zim-desktop-wiki/zim/plugins/pageindex/__init__.py", line 689, in get_any_children_expanded
    iter = model.iter_children(model.get_iter(path))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 876, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '5:0'

```

**Comment by bttrx** [comment]
Confirmed for Zim 0.75.2 on Linux Mint 20.2 MATE.
Restarting Zim usually helps for a while.
