### ISSUE TITLE
Notebook only able to be seen in fullscreen, unable to move window

### ISSUE THREAD

**Issue by jmrs2603** [zim-desktop-wiki/zim-desktop-wiki#2544]
Occasionally when closing a notebook, when it next opens it can only be viewed on the leftmost monitor after hitting F11 to fullscreen its window. It is not visible in any way when not in fullscreen. The window cannot be moved, closed or otherwise interacted with when not in fullscreen.

I've fixed this once with a blank notebook made within 5 minutes of the issue happening (it occuring on the first time the notebook was closed). Once I restarted my PC, the window was able to be seen when opened as a regular window and fullscreen functioned as it should instead of being the only way to view the window. This notebook was saved for the first time prior to being closed, but the bug has occured on notebooks that have never been saved.

 - Version 0.74.3
 - OS: Windows
 - Language: English

**Comment by bttrx** [comment]
Version 0.75.2 is available for Windows: https://zim-wiki.org/downloads/zim-desktop-wiki-0.75.2-setup-w64_x86.exe

So, why not upgrade and test again?

**Comment by jmrs2603** [comment]
I've upgraded and the issue is still present.

**Comment by introt** [comment]
Hi! Which version of Windows are you using? Does the gtk3-demo work correctly? Are you using the recommended settings for Windows detailed in #2007?

**Comment by realAllonZ** [comment]
I found this issue because I was looking for info on a similar issue that I am facing. 

A certain notebook window would randomly disappear and no longer be accessible even though it still appeared in the taskbar. Thanks to @jmrs2603  for sharing that it could still be accessed via the full screen shortcut. Very helpful when this issue appears and you just need quick access to some info.

I have been able to restore the notebook's accessibility by deleting the %AppData%\Roaming\zim\cache\zim folder so that the index would rebuild.

This happens quite frequently for me and is quite annoying. I would love to help get this issue resolved, so let me know if you need any further information to help resolve this issue.

Your assistance is greatly appreciated!

- Windows 11 Pro 64 23H2
- Zim 0.76.3
- No error message
- No steps to reproduce. Seems random
- zim.logs:

I am unsure the exact time of the event, but I am fairly certain that it is in one of the logs below. Otherwise, the error was not logged by Zim.

Created: September ‎2, ‎2025, ‏‎11:11:14 AM:
```
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
```

Created: ‎‎September ‎2, ‎2025, ‏‎10:52:57 AM:
```
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 3 HR Support:Markor Example Files:- Markor Zim-Wiki-Empty
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal share enchant myspell
ERROR: Exception in signal handler for file-row-inserted on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 108, in on_file_row_inserted
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal share enchant myspell
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 3 HR Support:Markor Example Files:- Markor Zim-Wiki-Empty
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal share enchant myspell
ERROR: Exception in signal handler for file-row-changed on <zim.notebook.index.files.FilesIndexer object at 0x00000189c21196d0>
Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/notebook/index/pages.py", line 128, in on_file_row_changed
  File "zim/notebook/layout.py", line 149, in map_filepath
  File "zim/notebook/layout.py", line 144, in map_file
  File "zim/notebook/page.py", line 139, in assertValidPageName
AssertionError: Not a valid page name: 4 IT:Warez:Soft:Zim:Spell Check: internal share enchant myspell
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
ERROR: Exception while parsing tag: search:
Traceback (most recent call last):
  File "zim/gui/pageview/__init__.py", line 832, in on_text_style_changed
AssertionError: No such tag: search
```

Created: ‎September ‎2, ‎2025, ‏‎08:52:07 AM:
```
ERROR: Exception in signal handler for process on <zim.templates.Template object at 0x0000015104abede0>
Traceback (most recent call last):
  File "zim/templates/expression.py", line 268, in __call__
  File "zim/templates/expression.py", line 380, in __getitem__
KeyError: 'place_cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zim/signals.py", line 369, in emit
  File "zim/templates/__init__.py", line 202, in do_process
  File "zim/templates/processor.py", line 82, in process
  File "zim/templates/processor.py", line 112, in __call__
  File "zim/templates/expression.py", line 282, in __call__
AssertionError: Not a valid function: place_cursor
```

**Comment by Pdgonz** [comment]
**On Windows 10.** Had this issue so often in recent years, I could york. Like the above posters, I could see the window but not open it. Sometimes this would happen when trying to open a second notebook. Usually the issue just went away. Then this week I had just updated to v.0.76.3, & yesterday it just got stuck, no escape. On opening, Zim would be visible while indexing, then become unavailable as consistent w. the other reports above. At the same time another semi-frequent issue for me was co-occurring, [bug #2778](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2778), 'Opening zim always starts a new instance'. Both issues cropped up anew, after I updated to latest Windows binaries on [Index of /downloads](https://zim-wiki.org/downloads/), 'zim-desktop-wiki-0.76.3-setup-w64_x86.exe'. And yes like the OP here above @jmrs2603 says, you can F11 for full-screen, but does not resolve issue. I tried deleting %AppData%\Roaming\zim\cache\zim folder as suggested by @realAllonZ above, but this did nothing on my case.
    **_So I rolled back to vsn. 0.73.5_**, I chose arbitrarily as before v. 0.74.x. **So far, all issues resolved.** Zim opens without indexing as per the older version, no seeing double (2 instances) and no mysterious window I can't open. As of this morning, I'm good to go, **_Zim seems 100% stable now on Windows 10._** I could experiment with v. 0.74.x when I have time. **Hope this helps anyone resolve the underlying issues,** from gtk3 or wut. **~Thanks!**
