### ISSUE TITLE
QuickNote plugin: KeyError: 'Config key "file:///home/robert/Notebooks/Notes" has not been defined'

### ISSUE THREAD

**Issue by bttrx** [zim-desktop-wiki/zim-desktop-wiki#2598]
**Describe the bug**
When you run the QuickNote plugin from command line _for the first time_, but press the Cancel button in the QuickNote dialog, you'll get a KeyError message.

As this error occurs only at the first start of the plugin, fixing has low priority, I think. Nevertheless, I wanted to file it hereby.

**To Reproduce**
1. Exit Zim
2. Remove file `$XDG_CONFIG_HOME/zim/quicknote.conf`
3. From Terminal run: `$ zim --plugin quicknote`
4. In dialog click `Cancel` button or press `Esc` key
5. See error

There is **no error**, when you repeat steps 3 and 4, because file `$XDG_CONFIG_HOME/zim/quicknote.conf` has been created already. Also **no error**, if you repeat steps 2 and 3, but click `OK` instead of `Cancel`.

**Expected behavior**
Just no error message after pressing `Esc` key. ;-)

**Screenshots**
```
ERROR: Exception in do_response()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 3132, in do_response
    self.save_uistate()
  File "/usr/lib/python3/dist-packages/zim/plugins/quicknote.py", line 378, in save_uistate
    self.config['Namespaces'][notebook] = self.form['namespace']
  File "/usr/lib/python3/dist-packages/zim/config/dicts.py", line 539, in __setitem__
    raise KeyError('Config key "%s" has not been defined' % k)
KeyError: 'Config key "file:///home/robert/Notebooks/Notes" has not been defined'
```

**Environment (please complete the following information):**
 - Version 0.75.2 (`deb http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu focal main`)
 - OS: Linux Mint 20.2 MATE
 - Language: German
 - Plugins: ~~do you use any custom plugins that were not included with zim? Can the bug be reproduced when these custom plugins are disabled?~~

**Comment by introt** [comment]
Thanks for the report! To reproduce, you need to have a default wiki set.

This patch seems to fix the issue, but I haven't studied the code to see whether it's the correct place to initialize that:

```diff
diff --git a/zim/plugins/quicknote.py b/zim/plugins/quicknote.py
index 0bf83bd0..aef887ab 100644
--- a/zim/plugins/quicknote.py
+++ b/zim/plugins/quicknote.py
@@ -373,6 +373,7 @@ class QuickNoteDialog(Dialog):
                self.uistate['open_page'] = self.open_page_check.get_active()
                if notebook is not None:
                        if self.uistate['new_page']:
+                               self.config['Namespaces'].setdefault(notebook, None, str)
                                self.config['Namespaces'][notebook] = self.form['namespace']
                        else:
                                self.config['Namespaces'][notebook] = self.form['page']
```
