### ISSUE TITLE
Crashes immediately

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#2603]
**Describe the bug**
```
This is zim 0.75.2
Platform: posix
Locale: sv_SE UTF-8
FS encoding: utf-8
Python: (3, 9, 18, 'final', 0)
PyGObject: (3, 42, 2)

======= Traceback =======
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 764, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 806, in _run_main_loop
    w = cmd.run()
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 268, in run
    notebook, pagelink = self.build_notebook()
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 240, in build_notebook
    notebook, uripagelink = build_notebook(notebookinfo) # can raise FileNotFound
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/__init__.py", line 130, in build_notebook
    notebook = Notebook.new_from_dir(folder)
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/notebook.py", line 268, in new_from_dir
    index = Index(cache_dir.file('index.db').path, layout)
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 66, in __init__
    self._db_connect()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 119, in _db_connect
    self._db_recover()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 136, in _db_recover
    self._db_init()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 139, in _db_init
    tables = [r[0] for r in self._db.execute(
OperationalError: no such column: table

```

**To Reproduce**
Install and try to run on FreeBSD 14.0. Crashes immediately after asking where to put the Notes (/hem/Text).

**Expected behavior**
I would like to be able to use this application.

**Screenshots**

**Environment (please complete the following information):**
 - Version: `0.75.2`
 - OS: `FreeBSD skrivmaskin 14.0-RELEASE-p6 FreeBSD 14.0-RELEASE-p6 #0: Tue Mar 26 20:26:20 UTC 2024     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64`
 - Language: `LANG=sv_SE.UTF-8`
 - Plugins: No.

**Additional context**

`HOME=/hem`

**Comment by jaap-karssenberg** [comment]
This is a weird one; this part of the code is rather stable for a long
time. This particular error happens when querying meta data of the SQLite
database. Could there be a dependency on a particular version of SQLIte?

**Comment by denverh2000** [comment]
I'm seeing this as well after upgrading FreeBSD from 13.2 to 14.1.  Here's my zim error report:
This is zim 0.75.2
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 9, 19, 'final', 0)
PyGObject: (3, 42, 2)

======= Traceback =======
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 764, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 806, in _run_main_loop
    w = cmd.run()
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 268, in run
    notebook, pagelink = self.build_notebook()
  File "/usr/local/lib/python3.9/site-packages/zim/main/__init__.py", line 240, in build_notebook
    notebook, uripagelink = build_notebook(notebookinfo) # can raise FileNotFound
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/__init__.py", line 130, in build_notebook
    notebook = Notebook.new_from_dir(folder)
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/notebook.py", line 268, in new_from_dir
    index = Index(cache_dir.file('index.db').path, layout)
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 66, in __init__
    self._db_connect()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 119, in _db_connect
    self._db_recover()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 136, in _db_recover
    self._db_init()
  File "/usr/local/lib/python3.9/site-packages/zim/notebook/index/__init__.py", line 139, in _db_init
    tables = [r[0] for r in self._db.execute(
OperationalError: no such column: "table" - should this be a string literal in single-quotes?

After poking at this for a while, I've figured out the following:
1.  if I comment out the offending line 139 it works.
2. if I uncomment that line after making a change to a notebook it will continue to work, but I have to make that change
3. if I try to create a new notebook I have to go through the same comment/uncomment process
4. if I try to access a different notebook it will fail again until I repeat that process
5. this happens even on a brand new system with only the minimum installed to be able to run this
6. I also tried the version of zim that I had been using on 13.2, but that failed the same way also

The version of sqlite my copy of zim is currently using is py39-sqlite3: 3.9.19_7.  I'm not sure what it was using with 13.2.  I could try building it with a different python version when I get a chance.

Thanks,

Denver

**Comment by denverh2000** [comment]
I tried with py311-sqlite3-3.11.9_7 but got the same results.  That's the only other version I can try at this point.

**Comment by denverh2000** [comment]
If you start zim with -f (flush index and force rebuilding) this problem returns for all notebooks.

I have a jail with
FreeBSD fbsd12.lan 12.2-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC  amd64
where zim work OK.  The version of sqlite there is:
sqlite3-3.38.5,1
On the 14.1 system it's:
sqlite3-3.46.0,1

If the problem is actually with sqlite, then it seems to be between 3.38 and 3.46.

Thanks,

Denver

**Comment by mexicarne** [comment]
I can reproduce this reliably by forcing to rebuild index database. But I have no issues with running zim.
My environment is FreeBSD 15, Python 3.11.9, sqlite 3.46.0. 

```python
[rm@cf ~]% zim --index --flush ~/Notebooks/Notes/
INFO: Connecting to database file: /home/rm/.cache/zim/notebook-home_rm_Notebooks_Notes/index.db
INFO: Flushing index
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/local/lib/python3.11/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zim/main/__init__.py", line 766, in _run_cmd
    cmd.run()
  File "/usr/local/lib/python3.11/site-packages/zim/main/__init__.py", line 582, in run
    notebook.index.flush()
  File "/usr/local/lib/python3.11/site-packages/zim/notebook/index/__init__.py", line 200, in flush
    self._db_init()
  File "/usr/local/lib/python3.11/site-packages/zim/notebook/index/__init__.py", line 139, in _db_init
    tables = [r[0] for r in self._db.execute(
                            ^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: "table" - should this be a string literal in single-quotes?
```

If I look at the index file that was created, then it's seems there are zim created tables:

```shell
[rm@cf ~]% sqlite3 /home/rm/.cache/zim/notebook-home_rm_Notebooks_Notes/index.db
SQLite version 3.46.0 2024-05-23 13:25:27
Enter ".help" for usage hints.
sqlite> .tables
files       links       pages       tags        tagsources  zim_index 
sqlite> SELECT name FROM sqlite_master WHERE type="table" and name NOT LIKE "sqlite%";
Parse error: no such column: "table" - should this be a string literal in single-quotes?
  SELECT name FROM sqlite_master WHERE type="table" and name NOT LIKE "sqlite%";
                              error here ---^
sqlite> 
sqlite> .quit
```

and the problem, it seems, is in double quotes in sql request. It works fine with single quotes:

```shell
sqlite> SELECT name FROM sqlite_master WHERE type="table";
Parse error: no such column: "table" - should this be a string literal in single-quotes?
  SELECT name FROM sqlite_master WHERE type="table";
                              error here ---^
sqlite> SELECT name FROM sqlite_master WHERE type='table';
zim_index
files
pages
links
tags
tagsources
sqlite> 
```

I swapped double quotes with single quotes in `zim/notebook/index/__init__.py` and `zim --index` now works for me:

broken:
```python
138     def _db_init(self):
139         tables = [r[0] for r in self._db.execute(
140             'SELECT name FROM sqlite_master '
141             'WHERE type="table" and name NOT LIKE "sqlite%"'
142         )] 
```

working:
```python
138     def _db_init(self):
139         tables = [r[0] for r in self._db.execute(
140             "SELECT name FROM sqlite_master "
141             "WHERE type='table' and name NOT LIKE 'sqlite%'"
142         )] 
```

**Comment by mexicarne** [comment]
And according to the docs, sqlite treats double quoted entities as keywords, not the string literals:
https://www.sqlite.org/lang_keywords.html

**Comment by denverh2000** [comment]
Yes, that fixes it, and makes sense.  Thanks for that.

Denver

**Comment by mexicarne** [comment]
So the reason why it breaks is the change in upstream sqlite 3.41.0. There was an option SQLITE_DBCONFIG_DQS_DDL that allowed to use double quotes for string literals to keep compatibility with mysql 3.x. Now it is disabled by default. That's the cause of zim breakage upon OS version update. So the correct solution is to fix zim's usage of double quotes in sql request, like above.

Reference: https://sqlite.org/quirks.html#dblquote
