### ISSUE TITLE
Zim wont open in macOS Sequoia

### ISSUE THREAD

**Issue by murattepegoz** [zim-desktop-wiki/zim-desktop-wiki#2665]
**Describe the bug**
Zim fails to start with an error dialog, attached.
I can try to collect more data if required, let me know please.

**To Reproduce**
Always reproducible.

**Screenshots**

**Environment (please complete the following information):**
 - Version: 0.75.2
 - OS: macos sequoia (15.0 and 15.1)
 - Plugins: default plugins.

**Additional context**
- Tried to remove zim and configuration files and re-install, didn't help.

"zim -D" output:
========================
zim 0.75.2

Copyright 2008 - 2023 Jaap Karssenberg <jaap.karssenberg@gmail.com> 

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mtepegoz@macbookair ~ % /Applications/Zim.app/Contents/MacOS/Zim -D
DEBUG: Can not import 'xdg.Mime' - falling back to 'mimetypes'
INFO: Can not import 'xdg.Mime' - falling back to 'mimetypes'
DEBUG: Loading config from: <ConfigFile: /Users/mtepegoz/Library/Application Support/org.zim-wiki.Zim/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x104df64d0>
INFO: This is zim 0.75.2
DEBUG: Python version is sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /Users/mtepegoz/Library/Application Support/org.zim-wiki.Zim/share
DEBUG: Set XDG_DATA_DIRS to [<LocalFolder: /Applications/Zim.app/Contents/Resources/share>]
DEBUG: Set XDG_CONFIG_HOME to /Users/mtepegoz/Library/Application Support/org.zim-wiki.Zim
DEBUG: Set XDG_CONFIG_DIRS to [<LocalFolder: /Applications/Zim.app/Contents/Resources/etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /Users/mtepegoz/Library/Caches/org.zim-wiki.Zim
DEBUG: Connecting to /tmp/zim-0.75.2-28ccff55
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-0.75.2-28ccff55
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x109076740>
DEBUG: Loading config from: /Users/mtepegoz/Notebooks/Notes/notebook.zim
DEBUG: Loading config from: /Users/mtepegoz/Notebooks/Notes/notebook.zim
DEBUG: Connecting to database file: /Users/mtepegoz/Library/Caches/org.zim-wiki.Zim/zim/notebook-Users_mtepegoz_Notebooks_Notes/index.db
DEBUG: Exception in main()
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 764, in _run_cmd
    self._run_main_loop(cmd)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 806, in _run_main_loop
    w = cmd.run()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 268, in run
    notebook, pagelink = self.build_notebook()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 240, in build_notebook
    notebook, uripagelink = build_notebook(notebookinfo) # can raise FileNotFound
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/__init__.py", line 130, in build_notebook
    notebook = Notebook.new_from_dir(folder)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/notebook.py", line 268, in new_from_dir
    index = Index(cache_dir.file('index.db').path, layout)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 66, in __init__
    self._db_connect()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 108, in _db_connect
    elif self.get_property('db_sortkey_format') != natural_sort_key(DB_SORTKEY_CONTENT):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/utils.py", line 137, in natural_sort_key
    bytestring = locale.strxfrm(string)
OSError: [Errno 22] Invalid argument
ERROR: Invalid argument
DEBUG: Running ErrorDialog

<img width="288" alt="Screenshot 2024-08-29 at 10 14 40 PM" src="https://github.com/user-attachments/assets/d3b87a04-cac4-44bb-b58c-73a90452d93f">

**Comment by dehesselle** [comment]
Confirmed on Sequoia public beta 6 (x86_64).
First step is that I'll update all dependencies and rebuild.

**Comment by dehesselle** [comment]
@murattepegoz Can you confirm that Meld launches for you? (It does for me.)
https://gitlab.com/dehesselle/meld_macos/-/releases/v3.22.2+68

That would be a valuable insight to have.

**Comment by dehesselle** [comment]
I have no existing notebooks, the error I'm getting on a clean system is different.
<details>
<summary>debug output</summary>

```
rudolph@Aquarius RAM % Zim.app/Contents/MacOS/Zim -D
DEBUG: Can not import 'xdg.Mime' - falling back to 'mimetypes'
INFO: Can not import 'xdg.Mime' - falling back to 'mimetypes'
DEBUG: Loading config from: <ConfigFile: /Users/rudolph/Library/Application Support/org.zim-wiki.Zim/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x10d306050>
INFO: This is zim 0.75.2
DEBUG: Python version is sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /Users/rudolph/Library/Application Support/org.zim-wiki.Zim/share
DEBUG: Set XDG_DATA_DIRS to [<LocalFolder: /Volumes/RAM/Zim.app/Contents/Resources/share>]
DEBUG: Set XDG_CONFIG_HOME to /Users/rudolph/Library/Application Support/org.zim-wiki.Zim
DEBUG: Set XDG_CONFIG_DIRS to [<LocalFolder: /Volumes/RAM/Zim.app/Contents/Resources/etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /Users/rudolph/Library/Caches/org.zim-wiki.Zim
DEBUG: Connecting to /tmp/zim-0.75.2-ea2d9fa3
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-0.75.2-ea2d9fa3
DEBUG: First time usage - prompt for notebook folder
DEBUG: Opening dialog "Add Notebook"
DEBUG: Opening dialog "Add Notebook"
2024-08-31 17:55:51.329 Zim[1897:90346] +[IMKClient subclass]: chose IMKClient_Legacy
DEBUG: Dialog response OK
DEBUG: Closed dialog "Add Notebook"
DEBUG: Loading config from: /Users/rudolph/Notebooks/Notes/notebook.zim
DEBUG: Loading config from: /Users/rudolph/Notebooks/Notes/notebook.zim
DEBUG: Connecting to database file: /Users/rudolph/Library/Caches/org.zim-wiki.Zim/zim/notebook-Users_rudolph_Notebooks_Notes/index.db
DEBUG: Operational error, init tabels
DEBUG: (Re-)Initializing database for index
WARNING: Overwriting possibly corrupt database: /Users/rudolph/Library/Caches/org.zim-wiki.Zim/zim/notebook-Users_rudolph_Notebooks_Notes/index.db
DEBUG: (Re-)Initializing database for index
DEBUG: Exception in main()
Traceback (most recent call last):
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 105, in _db_connect
    if self.get_property('db_version') != DB_VERSION:
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 161, in get_property
    c = self._db.execute('SELECT value FROM zim_index WHERE key=?', (key,))
sqlite3.OperationalError: no such table: zim_index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 117, in _db_connect
    self._db_init()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 155, in _db_init
    ''' % (DB_VERSION, natural_sort_key(DB_SORTKEY_CONTENT)))
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/utils.py", line 137, in natural_sort_key
    bytestring = locale.strxfrm(string)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 962, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 733, in run
    self._run_cmd(cmd, args) # test seam
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 764, in _run_cmd
    self._run_main_loop(cmd)
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 806, in _run_main_loop
    w = cmd.run()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 268, in run
    notebook, pagelink = self.build_notebook()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/main/__init__.py", line 240, in build_notebook
    notebook, uripagelink = build_notebook(notebookinfo) # can raise FileNotFound
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/__init__.py", line 130, in build_notebook
    notebook = Notebook.new_from_dir(folder)
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/notebook.py", line 268, in new_from_dir
    index = Index(cache_dir.file('index.db').path, layout)
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 66, in __init__
    self._db_connect()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 119, in _db_connect
    self._db_recover()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 136, in _db_recover
    self._db_init()
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/index/__init__.py", line 155, in _db_init
    ''' % (DB_VERSION, natural_sort_key(DB_SORTKEY_CONTENT)))
  File "/Volumes/RAM/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/utils.py", line 137, in natural_sort_key
    bytestring = locale.strxfrm(string)
OSError: [Errno 22] Invalid argument
ERROR: Invalid argument
DEBUG: Running ErrorDialog
```
</details>

**Comment by murattepegoz** [comment]
> @murattepegoz Can you confirm that Meld launches for you? (It does for me.) https://gitlab.com/dehesselle/meld_macos/-/releases/v3.22.2+68
> 
> That would be a valuable insight to have.

Meld works for me.

**Comment by emabo** [comment]
I have same issue, applying this patch, at least I can run Zim:

```
--- a/Zim/Contents/Resources/lib/python3.10/site-packages/zim/utils.py
+++ b/Zim/Contents/Resources/lib/python3.10/site-packages/zim/utils.py
@@ -136,7 +136,10 @@
 	try:
 		bytestring = locale.strxfrm(string)
 			# 8-bit byte string - enode to hex -- in pyton3 check if byte data type is handled better by sqlite3 and others
-	except MemoryError:
+	except (MemoryError, OSError, ValueError) as e:
+		# Catch possible exceptions from locale.strxfrm
+		print(string)
+		print(f"Error in strxfrm: {e}")
 		# Known python issue :(
 		bytestring = string

```

and I have following error:

```
DEBUG: Connecting to database file: /Users/emanu/Library/Caches/org.zim-wiki.Zim/zim/notebook-Users_emanu_Notebooks_Notes/index.db
Error in strxfrm: [Errno 22] Invalid argument
text_00001.00002.00003_unicode_αβγ_žžž
```

hope it can help.

**Comment by joshuamkite** [comment]
OK, so thanks to @dehesselle for demonstrating the command to run the app on mac from CLI with debug flag, and ChatGPT to interpret the output together with conversation to date in this thread I have a workaround (I have zim installed from HomeBrew):

Run with Different Locale: 

```bash
LC_ALL=C /Applications/Zim.app/Contents/MacOS/Zim -D
```

For now I can run upatched Zim installed from HomeBrew on Sequoia  reliably with this. I also set 

```bash
alias zim="LC_ALL=C /Applications/Zim.app/Contents/MacOS/Zim"
```

in my shell profile for convenience

**Comment by dehesselle** [comment]
That confirms it's a locale-thing, thank you both.

I think I'll bring all dependencies up-to-date first and then I need to dig in.

**Comment by dehesselle** [comment]
I have localized the problem.

Zim has no GUI setting to change the language, it relies on `LANG` being set. On macOS, `LANG` isn't set when launching from the UI (Launchpad, Finder, ...), so there's a little auto-detection magic happening in the background to do that. And that little magic trick doesn't work on Sequoia anymore.

Until I've fixed that, the workaround is to set `LANG` yourself. Either in the terminal as mentioned above or you can create a file `~/Library/Application Support/org.zim-wiki.Zim/zimapp.ini` with

```ini
[environment]
LANG=de
```
Substitute `de` with your own language code, of course :).

**Comment by dehesselle** [comment]
I need help confirming the fix. These are artifacts from my development branch (unsigned, you need to `xattr -r -d com.apple.quarantine Zim.app`), do they work for you? Remember to remove any previous workarounds in your terminal and/or `zimapp.ini`.

- Intel: https://gitlab.com/dehesselle/zim_macos/-/jobs/7885181880/artifacts/raw/Zim-0.75.2+292_x86_64.dmg
- Apple Silicon: https://gitlab.com/dehesselle/zim_macos/-/jobs/7885181881/artifacts/raw/Zim-0.75.2+292_arm64.dmg

**Comment by joshuamkite** [comment]
OK, I misspoke previously, I had installed zim from [dmg](https://gitlab.com/dehesselle/zim_macos/-/releases). Your [beta](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2665#issuecomment-2365265281) does work- from dock shortcut which I had not changed. But the font kerning is not great:

## Zim-0 75 2+264_arm64
<img width="872" alt="Zim-0 75 2+264_arm64" src="https://github.com/user-attachments/assets/2582dbaf-21da-42c9-bc04-67bbeaa2e538">

 ## Zim-0 75 2+292_arm64
<img width="872" alt="Zim-0 75 2+292_arm64" src="https://github.com/user-attachments/assets/dbe02c98-9d70-4bb8-8c46-85f6736cf1cf">

**Comment by joshuamkite** [comment]
Curiously with the beta I get the original error in this thread if I do 

```bash
/Applications/Zim.app/Contents/MacOS/Zim
```

from command line.

**Comment by dehesselle** [comment]
Before you run that in the terminal, what is the output from `echo $LANG`?

**Comment by joshuamkite** [comment]
```
Joshuas-Own-MacBook-Pro:~ joshua$ echo $LANG?
en_US.UTF-8?
Joshuas-Own-MacBook-Pro:~ joshua$ /Applications/Zim.app/Contents/MacOS/Zim
```

Interestingly, this is not my MacOS locale:

<img width="827" alt="Screenshot 2024-09-21 at 19 16 59" src="https://github.com/user-attachments/assets/dd55f278-3e08-44ab-8535-b189901acb8c">

**Comment by dehesselle** [comment]
This is crazy. The root problem is that on Sequoia, something doesn't like the hyphen in `$LANG` anymore. If you run
```bash
LANG=en_US.UTF8 /Applications/Zim.app/Contents/MacOS/Zim
```
it'll work. I'll add a workaround for that. 

Regarding font kerning, it'll be a dependency update that I need to identify and roll back.

**Comment by joshuamkite** [comment]
```bash
LANG=en_US.UTF8 /Applications/Zim.app/Contents/MacOS/Zim
``` 

gives same error for me: 

<img width="680" alt="Screenshot 2024-09-21 at 19 31 50" src="https://github.com/user-attachments/assets/2c798536-353a-4b8c-aa0b-d18eaf7bed14">

Thanks for all your efforts!

**Comment by dehesselle** [comment]
That I cannot reproduce. What about using `en` instead of `en_US.UTF8`?

**Comment by joshuamkite** [comment]
same with 

```bash
LANG=en_GB /Applications/Zim.app/Contents/MacOS/Zim
```

and
```bash
LANG=en /Applications/Zim.app/Contents/MacOS/Zim
```

and beta

**Comment by dehesselle** [comment]
One last shot: depending on how you've set up your shell, this might not be enough. Do a proper export first and see if that helps:
```bash
export LANG=en_US.UTF8
/Applications/Zim.app/Contents/MacOS/Zim
```

**Comment by joshuamkite** [comment]
Same. I am using Brew bash shell as per kerning illustration above

**Comment by dehesselle** [comment]
Strike the previous comment. Do you have `LC_ALL` set? That overrides everything else.

**Comment by joshuamkite** [comment]
It seems I do although I did not set it this way actively:

```bash
Joshuas-Own-MacBook-Pro:~ joshua$ printenv |ggrep -i lc
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
Joshuas-Own-MacBook-Pro:~ joshua$ locale
LANG="en_US.UTF8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
Joshuas-Own-MacBook-Pro:~ joshua$ 
```

**Comment by dehesselle** [comment]
This is a custom configuration. No `LC_` variables are set on my clean test environment.
Since you're using brew, that's likely the reason.
Can you `unset` all the `LC_` variables except for `LANG` and try again?

Because this produces the error for me
```bash
LC_ALL=en_US.UTF-8 LANG=en /Applications/Zim.app/Contents/MacOS/Zim
```
and this doesn't
```bash
LANG=en /Applications/Zim.app/Contents/MacOS/Zim
```

**Comment by joshuamkite** [comment]
Yes, this works:

<img width="1347" alt="Screenshot 2024-09-21 at 20 03 31" src="https://github.com/user-attachments/assets/8dcfb8f7-12af-4e55-8901-7d9b0c2ca696">

**Comment by dehesselle** [comment]
Ok. I know what I need to patch for the locale craziness.
Let's see if get lucky with the font kerning. Otherwise it'll take some time and lots of rebuilds.

**Comment by joshuamkite** [comment]
OK, thanks and good luck! The kerning issue is not a showstopper but it would be great to resolve it

**Comment by 3rgz88** [comment]
Following this thread - Zim on MacOS Sequoia was showing the "Invalid Argument / Close" message.  

Created zimapp.ini in  ~/Library/Application Support/org.zim-wiki.Zim/ with 

[environment]
LANG=en

restarted Zim.   

All working, thanks for the prompt response until the next version is released.

**Comment by au-dee-o-phile** [comment]
Made a GitHub account purely because of this issue, and am now following this thread. I can't get a zimapp.ini file to work, seemingly, but the Terminal commands do work. I do want to add a note that setting a different language just for Zim means that Zim will open as normal (in that different language, of course) — so it does seem to be that macOS doesn't set LANG unless it's been told to change it. Zim continues to show "Invalid argument" if you try setting the custom language setting to the same as your system's preferred language.

<img width="492" alt="Screenshot 2024-09-25 at 21 14 16" src="https://github.com/user-attachments/assets/a8481acf-c201-419d-be6e-a9c0c360a7e3">

**Comment by dominic16y** [comment]
the same issue here
when I open zim I got error message:

Invalid argument

here is my env.
LANG=zh_TW.UTF-8

then I do this:

create this file
~/Library/Application Support/org.zim-wiki.Zim/zimapp.ini

add context below:
[environment]
LANG=C

then solve problem

**Comment by floranon** [comment]
I'm sorry, but i'm new at github. Nevertheless, the previous workaround doesn't work for me.

   I just installed Sequoia 15.1.1 on my MacBook Air M2. Whatever version i had before, in the Summer, Zim was already failing. I had hoped that the upgrade would solve it.

   I uninstalled via
brew uninstall zim

   I reinstalled via
brew install zim

   I run zim 0.75.2 from an iTerm command line and get the error box which only says
Invalid argument

   Ran: env | grep LANG
LANG=en_US.UTF-8

   There was originally no directory at all at ~/Library/Application Support/org.zim-wiki.Zim/ so i created it. *Perhaps there is a Permissions issue now?* Then created ~/Library/Application Support/org.zim-wiki.Zim/zimapp.ini containing
[environment]
LANG=en_US.UTF8

   This fails. I first tried LANG=C, but that failed too.

   So sorry that it does not work at all for me now. This has been my main note-taking, journaling, organzing tool. zim is a great program when it works.

   I am subscribing to this issue. Thank you for your help.

@}-}--- Flora ---{-{@

**Comment by dehesselle** [comment]
The `zimapp.ini` feature is exclusive to the app (see the macOS section in [downloads](https://www.zim-wiki.org/downloads.html)) and not part of what you get when installing via Homebrew, Macports or the likes.

**Comment by floranon** [comment]
Wow, i didn't expect to be in a dialog. Thank you!

   I have never had to deal with a configuration file when installing via brew, but i'm open to learning. :)

   I am reading the https://www.zim-wiki.org/downloads.html page:

   I created a directory at ~/Library/Caches/org.zim-wiki.Zim . That did not solve it.

   I see that my PATH is:
% env | grep PATH
PATH=/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities

   That appears to include the path for zim:
% which zim
/opt/homebrew/bin/zim
   ...so i didn't add that. Unfortunately, it still doesn't work.

   I freely admit i'm bad at PATH and ln stuff. There is no /Applications/Zim.app , let alone Applications/Zim.app/Contents/Resources/bin . In general i'm not getting brew apps installed in /Applications. Perhaps that's my original problem and i need to talk to brew folk?

   Thank you, again, for the pointers.

flora

ps If this is not the correct place for this dialog, please let me know.

**Comment by dehesselle** [comment]
I think you're getting things mixed up:

-  The workaround being discussed here to set the `LANG` in `zimapp.ini` is only for the Zim app that you can download via the website (link above!), not for what you install via Homebrew. Those two are completely different things.

- This has nothing to do with `PATH`.

**Comment by floranon** [comment]
Thank you again.

Okay. Yes, i did not understand that to be the case.

I will use other tools until this is fixed.

Be well.

**Comment by dominic16y** [comment]
To floranon:

here is what you should do:
execute command:
```bash
brew uninstall zim

``` 

then download this [file](https://gitlab.com/api/v4/projects/30529415/packages/generic/zim_macos/0.75.2%2B264/Zim-0.75.2+264_arm64.dmg) to install zim

when you install done

create this file
~/Library/Application Support/org.zim-wiki.Zim/zimapp.ini

add context below:
[environment]
LANG=C

then you can use zim

**Comment by dehesselle** [comment]
I need you all to test a release candidate.
Minimum OS requirements have changed, it's Big Sur now for both Intel and Apple Silicon.

https://gitlab.com/dehesselle/zim_macos/-/pipelines/1609596969/builds

- Please remove any language/locale based entries from your `zimapp.ini`.
- Does Zim start in your system's language?
- If you want to set another language via `LANG`, use `UTF8` as suffix (lose the hyphen!), e.g. `de_DE.UTF8`.

Please report back here with:
- if it works or not
- your OS version and architecture
- output from running the `locale` command in your terminal

**Comment by joshuamkite** [comment]
Works 

- MacOS 15.2 (24C101)

```
ls ~/Library/Application\ Support/org.zim-wiki.Zim/
gtk-3.0 share   zim
```

```
uname -sa
Darwin Joshuas-Own-MacBook-Pro.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 18:56:34 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6020 arm64
```
```
locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Font kerning still impaired, as before, acknowledged not the focus here

**Comment by dehesselle** [comment]
I'm no longer confident that I can fix the font kerning issue. The original idea was to downgrade certain libraries to get back to previous behavior, but some updates fix major issues (garbled fonts) and I'm not going back on them, which basically blocks relevant downgrades.
There's still some things left that I can update further to their latest versions, so there's a bit of hope. But if that doesn't help, I need somebody else to investigate this.

**Comment by joshuamkite** [comment]
> I'm no longer confident that I can fix the font kerning issue. The original idea was to downgrade certain libraries to get back to previous behavior, but some updates fix major issues (garbled fonts) and I'm not going back on them, which basically blocks relevant downgrades. There's still some things left that I can update further to their latest versions, so there's a bit of hope. But if that doesn't help, I need somebody else to investigate this.

Understood, thanks for update and efforts!

**Comment by dehesselle** [comment]
There is actually something you can do to help which only requires a bit of experimentation: we can manipulate GTK's appearance with CSS.

Create a file `~/Library/Application Support/org.zim-wiki.Zim/gtk-3.0/gtk.css` and add
```css
*{ 
    font-family: "SF Pro";
 }
```

That already improves things a lot. What settings are good to become a default for the app? I've chosen SF Pro for this example because it's default system font on macOS. Documentation for available settings is here: https://docs.gtk.org/gtk3/css-properties.html

**Comment by purejava** [comment]
Thanks for your effort @dehesselle.

Works too for MacOS 15.2 (24C101) / x86_64
```
locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by joshuamkite** [comment]
@dehesselle Thanks for the [suggestion](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2665#issuecomment-2568562426). Setting the font is a massive improvement. I have tried configuring a few other properties based on your link but these either made things worse (specifying kerning); made no difference (defining window corner radiuses and shadows), or revealed that many of the other apps on my Mac are already inconsistent with one another (various scrollbar properties). I did try specifying fallback fonts but it didn't work for me and there seems little point since we are targeting versions where SF Pro is already included. I would say good to go with simply defining the font as you have suggested- it is simple, clear and usable. Thanks again!

**Comment by pentallelogram** [comment]
works for MacOS 15.1 (24B2083) / arm64

```
locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

And the font-family selector in gtk.css helps kerning a lot. Thank you!

**Comment by dehesselle** [comment]
Thanks for helping out so far. I think we're ready. Please test this (remove locale settings, remove CSS settings) and see if it works out of the box as expected:
https://gitlab.com/dehesselle/zim_macos/-/pipelines/1611461559/builds

If nothing unexpected happens, proper release later this weekend.

**Comment by joshuamkite** [comment]
Works well for me!

- MacOS 15.2 (24C101) ARM
- No css or ini files

**Comment by dehesselle** [comment]
Released, closing.

**Comment by stuaxocabinetoffice** [comment]
> There is actually something you can do to help which only requires a bit of experimentation: we can manipulate GTK's appearance with CSS.
> 
> Create a file `~/Library/Application Support/org.zim-wiki.Zim/gtk-3.0/gtk.css` and add
> 
> *{ 
>     font-family: "SF Pro";
>  }
> That already improves things a lot. What settings are good to become a default for the app? I've chosen SF Pro for this example because it's default system font on macOS. Documentation for available settings is here: https://docs.gtk.org/gtk3/css-properties.html

Is there an upstream issue to fix this in Gtk itself ?

**Comment by dehesselle** [comment]
It's not a GTK issue; my guess is it's a Pango issue, but it hasn't been properly identified yet (AFAIK).
