### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Signum** [zim-desktop-wiki/zim-desktop-wiki#425]
Today when I started my Zim notebook I just had my "Journal" but no other pages in the index. Reindexing didn't help.
Starting Zim in debug mode revealed:

```
$ zim -D
Gtk-Message: 09:37:05.587: Failed to load module "atk-bridge"
INFO: This is zim 0.68
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/chaas/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/xfce4>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/chaas/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/chaas/.cache
DEBUG: Connecting to /tmp/zim-chaas/primary-0.68-e63203e4
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Registered object line
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-chaas/primary-0.68-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f7051745890>
DEBUG: Loading config from: /home/chaas/owncloud/SYNC/Notebooks/Performance/notebook.zim
DEBUG: Wrote /home/chaas/.config/zim/notebooks.list
DEBUG: Loading config from: /home/chaas/owncloud/SYNC/Notebooks/Performance/notebook.zim
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x7f70510e00d0>
DEBUG: Loading config from: <ConfigFile: /home/chaas/.config/zim/preferences.conf>
DEBUG: Loading plugin: attachmentbrowser
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: versioncontrol
INFO: No VCS detected
DEBUG: Gtk version is (2, 24, 32)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: /home/chaas/.config/zim/style.conf>
DEBUG: Autosave interval: 15 - use threads: True
DEBUG: Loading config from: /home/chaas/.cache/zim/notebook-home_chaas_owncloud_SYNC_Notebooks_Performance/state.conf
DEBUG: Accelmap: /home/chaas/.config/zim/accelmap
INFO: Open page: Journal:2014:03:03 (Journal:2014:03:03)
DEBUG: Found template 'Journal' for Journal:2014:03:03
INFO: Loading template from: /usr/share/zim/templates/wiki/Journal.txt
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /home/chaas/owncloud/SYNC/Notebooks/Performance/Journal
ERROR: Error while indexing: Journal
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 111, in _update_iter_inner
    self.update_folder(node_id, folder)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 244, in update_folder
    self.delete_folder(child_id)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 276, in delete_folder
    self.delete_folder(child_id) # recurs
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 276, in delete_folder
    self.delete_folder(child_id) # recurs
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 276, in delete_folder
    self.delete_folder(child_id) # recurs
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 276, in delete_folder
    self.delete_folder(child_id) # recurs
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/files.py", line 276, in delete_folder
    self.delete_folder(child_id) # recurs
```
The last two lines repeated many times and then…

```
RuntimeError: maximum recursion depth exceeded while calling a Python object
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
```

Zim started with just showing the Journal.

I deleted ~/.cache/zim and restarted Zim but that did not change anything.

I worked around it by increasing Python's maximum recursion depth to 1500. Then Zim started and now it starts properly again with the standard recursion depth. So the problem is solved for me but there seems to be a problem anyway.

**Comment by jaap-karssenberg** [comment]
I believe this is fixed in zim 0.70. If similar issue is seen in zim 0.70 or newer, please open a new report.
