### ISSUE TITLE
Install fails on MacOS 10.13.4 and Homebrew

### ISSUE THREAD

**Issue by giacecco** [zim-desktop-wiki/zim-desktop-wiki#444]
I've followed the instructions at http://zim-wiki.org/install.html but the `./setup.py install` stage always fail, whether with or without sudo, with:

```
...
running install_egg_info
Removing /usr/local/lib/python2.7/site-packages/zim-0.68-py2.7.egg-info
Writing /usr/local/lib/python2.7/site-packages/zim-0.68-py2.7.egg-info
Trying: update-desktop-database
error: [Errno 2] No such file or directory
$
```

Running directly from the source files works nicely.

I've also noticed that `./test.py` fails with:

```
$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    import tests
  File "/Users/giacecco/Downloads/zim-0.68/tests/__init__.py", line 175, in <module>
    from zim.newfs import LocalFolder
  File "/Users/giacecco/Downloads/zim-0.68/zim/__init__.py", line 184, in <module>
    import zim.environ # initializes environment parameters
  File "/Users/giacecco/Downloads/zim-0.68/zim/environ.py", line 16, in <module>
    from zim.fs import ENCODING, isdir
  File "/Users/giacecco/Downloads/zim-0.68/zim/fs.py", line 130, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/Users/giacecco/Downloads/zim-0.68/zim/signals.py", line 8, in <module>
    import gobject
ImportError: No module named gobject
$
```

... but pygobject is installed using Homebrew.

Any suggestions? Thanks.

**Comment by jaap-karssenberg** [comment]
Apparently gobject is not found. SO although it is installed something may be wrong with the search path.

Next release will be Gtk3 based and use "gi" instead of "gobject" hope that makes things easier.
