### ISSUE TITLE
Flatpak sandbox / direct Wayland support

### ISSUE THREAD

**Issue by robertvazan** [zim-desktop-wiki/zim-desktop-wiki#571]
Zim is so awesome. As if it was designed for me.

There's one issue I found though. When I use the flatpak version on Wayland desktop and disable X access via flatpak overrides, Zim fails to start, because it requires the X<->Wayland proxy to run under Wayland. This is probably because the version of Gtk used in Zim is too old to support direct Wayland connection. There is therefore no hope of running Zim reasonably sandboxed. Would it be possible to upgrade Gtk or fix whatever issues is causing this?

This is what I get on console:

```
$ flatpak run org.zim_wiki.Zim
WARNING: /app/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)

WARNING: /app/lib/python2.7/site-packages/zim/gui/clipboard.py:477: GtkWarning: IA__gtk_clipboard_get_for_display: assertion 'display != NULL' failed
  self.clipboard = gtk.Clipboard(selection=atom)

ERROR: Exception in main()
Traceback (most recent call last):
  File "/app/lib/python2.7/site-packages/zim/main/__init__.py", line 850, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/app/lib/python2.7/site-packages/zim/main/__init__.py", line 631, in run
    self._run_cmd(cmd, args) # test seam
  File "/app/lib/python2.7/site-packages/zim/main/__init__.py", line 661, in _run_cmd
    self._run_main_loop(cmd)
  File "/app/lib/python2.7/site-packages/zim/main/__init__.py", line 688, in _run_main_loop
    from zim.gui.widgets import gtk_window_set_default_icon
  File "/app/lib/python2.7/site-packages/zim/gui/__init__.py", line 41, in <module>
    from zim.gui.pathbar import NamespacePathBar, RecentPathBar, RecentChangesPathBar, HistoryPathBar
  File "/app/lib/python2.7/site-packages/zim/gui/pathbar.py", line 10, in <module>
    from zim.gui.clipboard import \
  File "/app/lib/python2.7/site-packages/zim/gui/clipboard.py", line 595, in <module>
    Clipboard = ClipboardManager("CLIPBOARD") #: Singleton object for the default clipboard
  File "/app/lib/python2.7/site-packages/zim/gui/clipboard.py", line 477, in __init__
    self.clipboard = gtk.Clipboard(selection=atom)
RuntimeError: could not create GtkClipboard object
```

**Comment by jaap-karssenberg** [comment]
There is a release candidate out now for Gtk3 based version.

Afraid I do not handle flatpack packaging myself so will close this report here. Please report towards packager.

**Comment by robertvazan** [comment]
Opened [new issue](https://github.com/flathub/org.zim_wiki.Zim/issues/4) for the flatpak package.

**Comment by robertvazan** [comment]
Flatpak package was updated today. After disabling X11, Zim continues to work smoothly. Thank you.
