### ISSUE TITLE
Default text editor can't be set in the settings

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#612]
Happens with Zim 0.70-rc1 on Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
You mean the "applications" tab in the preferences dialog ?

Works fine in my testing, please add more information on your error

**Comment by sojusnik** [comment]
```
$ zim --debug
INFO: This is zim 0.70-rc1
DEBUG: Python version is sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/sojusnik/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/gnome-xorg>, <Dir: /home/sojusnik/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/sojusnik/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-gnome-xorg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/sojusnik/.cache
DEBUG: Connecting to /tmp/zim-sojusnik/primary-0.70-rc1-e63203e4
DEBUG: Got error in dispatch: No such file or directory
WARNING: Could not find all icon sizes for the application icon
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-sojusnik/primary-0.70-rc1-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7ff330590160>
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/state.conf
DEBUG: New extendable: <zim.notebook.notebook.Notebook object at 0x7ff330590fd0>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: VCS detected: git - /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/style.conf>
DEBUG: Autosave interval: 10 - use threads: True
DEBUG: New extendable: <pageview.PageView object at 0x7ff33055ac60 (zim+gui+pageview+PageView at 0x22af6d0)>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linesorter.LineSorterPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tags.TagsPageViewExtension'>
INFO: Open page: Sonstiges:Filme:Spielfilme (Sonstiges:Filme:Spielfilme)
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7ff3305aa9d8 (zim+gui+mainwindow+MainWindow at 0x225a270)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
INFO: Running: ('git', 'status', '--porcelain') (cwd: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines)
ERROR: Failed loading extension <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'> for plugin <zim.plugins.versioncontrol.VersionControlPlugin object at 0x7ff337e84240>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 455, in _extend
    ext = ext_class(plugin, obj)
  File "/usr/lib/python3/dist-packages/zim/plugins/versioncontrol/__init__.py", line 130, in __init__
    self.on_preferences_changed(None, start=True)
  File "/usr/lib/python3/dist-packages/zim/plugins/versioncontrol/__init__.py", line 147, in on_preferences_changed
    self.do_save_version_async()
  File "/usr/lib/python3/dist-packages/zim/plugins/versioncontrol/__init__.py", line 177, in do_save_version_async
    self._autosave_thread = op.thread
AttributeError: 'SimpleAsyncOperation' object has no attribute 'thread'
DEBUG: Accelmap: /home/sojusnik/.config/zim/accelmap
DEBUG: No autosave version needed - no changes
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: show_preferences
ERROR: Could not load plugin autocompletion
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/preferencesdialog.py", line 341, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 431, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3/dist-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/home/sojusnik/.local/share/zim/plugins/autocompletion.py", line 22, in <module>
    from zim.plugins import PluginClass, WindowExtension, extends
ImportError: cannot import name 'WindowExtension'
ERROR: Could not load plugin zim-zotero-plugin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/preferencesdialog.py", line 341, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 431, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3/dist-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/home/sojusnik/.local/share/zim/plugins/zim-zotero-plugin/__init__.py", line 8, in <module>
    from zim.plugins import PluginClass, extends, WindowExtension
ImportError: cannot import name 'extends'
DEBUG: Loading description for plugin: distractionfree
DEBUG: Opening dialog "Einstellungen"
DEBUG: Loading config from: /usr/share/applications/org.gnome.gedit.desktop
DEBUG: Loading config from: /home/sojusnik/.local/share/applications/Verknüpfung mit Zotero.desktop
DEBUG: Loading config from: /usr/share/applications/libreoffice-writer.desktop
DEBUG: Loading config from: /usr/share/applications/org.gnome.gedit.desktop
DEBUG: Loading config from: /usr/share/applications/vim.desktop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/preferencesdialog.py", line 447, in on_set_texteditor
    CustomizeOpenWithDialog(self.dialog, 'text/plain').run()
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 1013, in __init__
    self.reload()
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 1032, in reload
    combo.append(app)
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 1089, in append
    pixbuf = application.get_pixbuf(Gtk.IconSize.MENU)
  File "/usr/lib/python3/dist-packages/zim/gui/applications.py", line 803, in get_pixbuf
    if zim.fs.isfile(icon):
AttributeError: module 'zim.fs' has no attribute 'isfile'
```
