### ISSUE TITLE
test.py failed on Fedora 28

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#629]
currently at c933056461

test result under plain X11 session:
[test_report_xorg.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/2782099/test_report_xorg.txt)

test result under xvfb:
[test_report_xvfb.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/2782104/test_report_xvfb.txt)

**Comment by jaap-karssenberg** [comment]
There are 3 errors there
- default application for "text/plain" is not found
- test data from "tests/data/formats" is not found
- file links are resolved as absolute rather than relative links

Suggests that something weird is going on with the working directory and/or sandbox of the test. Are you running the tests with the source folder as PWD ?

**Comment by cheese** [comment]
> Suggests that something weird is going on with the working directory and/or sandbox of the test. Are you running the tests with the source folder as PWD ?
Yes. PWD is /run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/, and it is a git working directory.

**Comment by jaap-karssenberg** [comment]
With the latest patch about half of the error should be gone. Still working on issues related to default application.

**Comment by jaap-karssenberg** [comment]
I believe I addressed all errors now. Could you re-test please ?

**Comment by cheese** [comment]
Only the two tests that complain default application for "text/plain" is not found persist.

```
Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/applications.py", line 650, in edit_file
    open_file(widget, file, mimetype='text/plain', callback=check_close_dialog)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/applications.py", line 484, in open_file
    raise NoApplicationFoundError('No Application found for: %s' % mimetype)
zim.gui.applications.NoApplicationFoundError: No Application found for: text/plain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/uiactions.py", line 961, in testEditPageSource
    self.uiactions.edit_page_source()
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/uiactions.py", line 367, in edit_page_source
    edit_file(self.widget, self.page.source, istextfile=True)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/applications.py", line 652, in edit_file
    app = AddApplicationDialog(widget, 'text/plain').run()
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/widgets.py", line 2945, in run
    TEST_MODE_RUN_CB(self)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/__init__.py", line 472, in _callback
    self._default_handler(handler, dialog)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/__init__.py", line 478, in _default_handler
    raise AssertionError('Expected dialog of class %s, but got %s instead' % (cls, dialog.__class__))
AssertionError: Expected dialog of class <class 'zim.gui.widgets.MessageDialog'>, but got <class 'zim.gui.applications.AddApplicationDialog'> instead
```
