### ISSUE TITLE
test.py failed on Fedora Rawhide/30

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#640]
currently at 0.70-rc2

test result under X11 session:
[test_report.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/2803905/test_report.txt)

**Comment by jaap-karssenberg** [comment]
Whole bunch of StopIterator issues seem due to behavior change in python 3.7

Last error is due to different naming of mimetype, will fix test suite

**Comment by cheese** [comment]
At d7056354, there is still errors about the server:

```
ERROR: runTest (tests.main.TestServer)

Traceback (most recent call last):
  File "/usr/lib64/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/main.py", line 171, in runTest
    re = urlopen('http://localhost:8080')
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/main.py", line 174, in runTest
    cmd.server.shutdown()
AttributeError: 'ServerCommand' object has no attribute 'server'
```

**Comment by jaap-karssenberg** [comment]
I've seen that one, but it is not persistent. Re-running the test usually
it passes.

Need to improve the timing handshake.
