### ISSUE TITLE
errors thrown when loading calendar and sourceview in Flatpak

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#644]
Currently at c6a93192e8. Starting zim in Flatpak environment will show these backtrace.
After that, the main program is started properly.

```
$ flatpak run org.zim_wiki.Zim -D
ERROR: Exception while loading plugin: calendar
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 361, in load_plugins_from_preferences
    self.load_plugin(name)
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 459, in load_plugin
    klass = self.get_plugin_class(name)
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 413, in get_plugin_class
    mod = get_module(modname)
  File "/app/lib/python3.5/site-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
ImportError: No module named 'zim.plugins.calendar'
Gtk-Message: 15:56:46.214: Failed to load module "pk-gtk-module"
ERROR: Exception while loading plugin: sourceview
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 361, in load_plugins_from_preferences
    self.load_plugin(name)
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 459, in load_plugin
    klass = self.get_plugin_class(name)
  File "/app/lib/python3.5/site-packages/zim/plugins/__init__.py", line 413, in get_plugin_class
    mod = get_module(modname)
  File "/app/lib/python3.5/site-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/app/lib/python3.5/site-packages/zim/plugins/sourceview.py", line 144, in <module>
    class SourceViewBuffer(GtkSource.Buffer):
AttributeError: 'NoneType' object has no attribute 'Buffer'
```

**Comment by jaap-karssenberg** [comment]
The "calendar" message is one time only as the plugin has been renamed

**Comment by cheese** [comment]
The second error seems not fixed

**Comment by jaap-karssenberg** [comment]
Yes - stupid mistake on my part :(

**Comment by jaap-karssenberg** [comment]
OK, should be repaired now with f5ab951
