### ISSUE TITLE
test.py failed within Flatpak env with org.gnome.Platform 3.30 runtime

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#652]
Currently on d705635467

```
ERROR: runTest (tests.package.TestGit)

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/package.py", line 38, in runTest
    unknown = subprocess.check_output(['git', 'clean', '-dn'])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

FAIL: runTest (tests.widgets.TestFileDialog)

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/widgets.py", line 372, in runTest
    dialog.assert_response_ok()
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/gui/widgets.py", line 2983, in assert_response_ok
    raise AssertionError('%s.do_response_ok() did not return True' % self.__class__.__name__)
AssertionError: FileDialog.do_response_ok() did not return True

FAIL: runTest (tests.plugins.TestPlugins)

Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/tests/plugins.py", line 145, in runTest
    self.assertGreaterEqual(len(notebook.__zim_extension_objects__), 3)
AssertionError: 2 not greater than or equal to 3


```

**Comment by cheese** [comment]
ERROR: runTest (tests.package.TestGit) is not fixed

**Comment by jaap-karssenberg** [comment]
Correct - if you run from git source dir you need git present. If you want
to test without git test from a folder that does not have a ".git" like a
clean build directory.
