### ISSUE TITLE
Usage of appindicator in trayicon plugin has not been ported to GI-based

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#691]
In zim/plugins/trayicon.py, appindicator is being imported directly.

**Comment by jaap-karssenberg** [comment]
Updated the interface, but can't test on this system, please give it a try

**Comment by cheese** [comment]
'AppIndicator3' should be used instead of 'AppIndicator'.
https://lazka.github.io/pgi-docs/#AppIndicator3-0.1

```
diff --git a/zim/plugins/trayicon.py b/zim/plugins/trayicon.py
index fe9b814c..a8ad45bf 100644
--- a/zim/plugins/trayicon.py
+++ b/zim/plugins/trayicon.py
@@ -17,8 +17,8 @@ from zim.gui.mainwindow import MainWindowExtension
 # Try if we are on Ubunutu with app-indicator support
 try:
        import gi
-       gi.require_version('AppIndicator', '0.1')
-       from gi.repository import AppIndicator
+       gi.require_version('AppIndicator3', '0.1')
+       from gi.repository import AppIndicator3 as AppIndicator
 except:
        AppIndicator = None
```
After applying this fix, the code needs further porting:

```
DEBUG: Loading description for plugin: trayicon
DEBUG: Loading plugin: trayicon
DEBUG: Load extension: <class 'zim.plugins.trayicon.TrayIconMainWindowExtension'>
DEBUG: Add window: StatusIconTrayIcon
DEBUG: Loading description for plugin: trayicon
DEBUG: Opening dialog "Configure Plugin"
DEBUG: Dialog response OK
ERROR: Exception in signal handler for changed on <ConfigDict:
  'classic': False,
  'standalone': False
>
Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/signals.py", line 365, in emit
    r = handler(self, *args)
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/plugins/trayicon.py", line 102, in on_preferences_changed
    self.load_trayicon()
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/plugins/trayicon.py", line 105, in load_trayicon
    set_global_trayicon(self.preferences['classic'])
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/plugins/trayicon.py", line 49, in set_global_trayicon
    new = cls()
  File "/run/media/cheese/cheesenotes/upstream/zim-desktop-wiki/zim/plugins/trayicon.py", line 314, in __init__
    AppIndicator.CATEGORY_APPLICATION_STATUS
  File "/usr/lib64/python3.6/site-packages/gi/module.py", line 138, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.AppIndicator3' object has no attribute 'CATEGORY_APPLICATION_STATUS'
DEBUG: Closed dialog "Configure Plugin"
```

**Comment by jaap-karssenberg** [comment]
Thanks for the hint - with the right library now it also works in my own testing :)
