### ISSUE TITLE
quicknote dialog fails to open when no text is submitted

### ISSUE THREAD

**Issue by rhertzog** [zim-desktop-wiki/zim-desktop-wiki#717]
I have a shortcut running "zim --plugin quicknote" that now fails with 0.70~rc3:
```
$ zim --plugin quicknote
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 915, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 684, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 707, in _run_cmd
    if cmd.run_local():
  File "/usr/lib/python3/dist-packages/zim/plugins/quicknote.py", line 138, in run_local
    dialog = self.build_dialog()
  File "/usr/lib/python3/dist-packages/zim/plugins/quicknote.py", line 157, in build_dialog
    text=self.get_text(),
  File "/usr/lib/python3/dist-packages/zim/plugins/quicknote.py", line 127, in get_text
    assert isinstance(text, str), '%r is not decoded' % text
AssertionError: None is not decoded
```

The error goes away if I add "text=foobar" on the command line. It seems perfectly legit to not submit any text if the goal is that the user inputs the note to add...

This is a regression of the Python3/GTK3 port.

**Comment by jaap-karssenberg** [comment]
Fixed already in master in commit 9571201224e5a169229449391f2e5e437b2ff2b6
