### ISSUE TITLE
Formatting lost when end of line is selected for superscript or subscript

### ISSUE THREAD

**Issue by bitinerant** [zim-desktop-wiki/zim-desktop-wiki#763]
1. Type these 2 lines in Zim without formatting:
```
x2
y
```
2. Highlight the `2` and the rest of the line
3. Click Format > Superscript
4. Go to another Zim page and come back

After step 3, Zim displays the text as expected - the `2` is superscripted. However, after step 4, the formatting is lost and text becomes:

```
x^{2
}y
```
I would expect the displayed text to not change in any way when navigating away and back.

**Comment by Nick222** [comment]
Xubuntu 18.10
Zim 0.70

After some experiments such above - I received:

ERROR: Failed to save page: *****
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4796, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 363, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 490, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 481, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 503, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 709, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 720, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 736, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Running SavePageErrorDialog
ERROR: Похоже, вы нашли ошибку
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4796, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 363, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 490, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 481, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 503, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 709, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 720, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 736, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Store page in background: *****
ERROR: Error in background save
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 519, in _store_page_async_thread_main
    page._store_tree(parsetree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 503, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 709, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 720, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 736, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Last auto-save resulted in error, re-try in foreground
DEBUG: Saving page: *****
DEBUG: Store page: *****
ERROR: Failed to save page: *****
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4796, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 363, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 490, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 481, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 503, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 709, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 720, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 736, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None
DEBUG: Running SavePageErrorDialog
ERROR: Похоже, вы нашли ошибку
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4796, in save_page_now
    self.notebook.store_page(page)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 363, in wrapper
    return method(notebook, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 490, in store_page
    page._store()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 481, in _store
    self._store_tree(tree)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 503, in _store_tree
    self._last_etag = self.source_file.writelines_with_etag(lines, self._last_etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 709, in writelines_with_etag
    return self._write_with_etag(self.writelines, lines, etag)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 720, in _write_with_etag
    if not self.verify_etag(etag):
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 736, in verify_etag
    raise AssertionError('Invalid etag: %r' % etag)
AssertionError: Invalid etag: None

(zim:30566): Gtk-WARNING **: 18:42:56.733: GtkTextView - did not receive focus-out-event. If you
connect a handler to this signal, it must return
FALSE so the text view gets the event as well
WARNING: /usr/lib/python3/dist-packages/zim/gui/pageview.py:4932: Warning: Source ID 10483 was not found when attempting to remove it
  GObject.source_remove(id)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 415, in do_page_activated
    self.navigation.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4953, in open_page
    return self._real_navigation.open_page(*arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/navigation.py", line 17, in open_page
    self.window.open_page(path)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 756, in open_page
    raise AssertionError('Could not save page') # XXX - shouldn't this lead to dialog ?
AssertionError: Could not save page

**Comment by bitinerant** [comment]
I am using Zim 0.70-rc3 on Ubuntu 18.04

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * Reproduces when selecting across line boundary
  * Why not broken on line boundary like other tags ?
  * Link as test case to rework for tokenlist serialization #114

**Comment by jaap-karssenberg** [comment]
Fixed as part of cd5788effe4a9d30d929de45ac721fb1bb619aa4
