### ISSUE TITLE
Create table error

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#777]
Xubuntu 18.10
Zim 0.70

Menu: Insert - Table

In table-window add 3 columns and give it`s names

Then in terminal:

DEBUG: Opening dialog "Вставить таблицу"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 1041, in on_add_new_column
    self.treeview.set_cursor_on_cell(model.get_path(newiter), self.treeview.get_column(0), start_editing=True)
TypeError: Gtk.TreeView.set_cursor_on_cell() takes exactly 5 non-keyword arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 1041, in on_add_new_column
    self.treeview.set_cursor_on_cell(model.get_path(newiter), self.treeview.get_column(0), start_editing=True)
TypeError: Gtk.TreeView.set_cursor_on_cell() takes exactly 5 non-keyword arguments (3 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 1041, in on_add_new_column
    self.treeview.set_cursor_on_cell(model.get_path(newiter), self.treeview.get_column(0), start_editing=True)
TypeError: Gtk.TreeView.set_cursor_on_cell() takes exactly 5 non-keyword arguments (3 given)

Error-window:

Package: zim 0.70-ubuntu18.10.1 [origin: LP-PPA-jaap.karssenberg-zim]
PackageArchitecture: all
ProcCpuinfoMinimal:
 processor	: 3
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 30
 model name	: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
 stepping	: 5
 microcode	: 0xa
 cpu MHz		: 2707.123
 cache size	: 8192 KB
 physical id	: 0
 siblings	: 4
 core id		: 3
 cpu cores	: 4
 apicid		: 6
 initial apicid	: 6
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 11
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
 bogomips	: 5619.54
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 36 bits physical, 48 bits virtual
 power management:
ProcVersionSignature: Ubuntu 4.18.0-17.18-generic 4.18.20
Python3Details: /usr/bin/python3.6, Python 3.6.7, python3-minimal, 3.6.7-1~18.10
PythonDetails: /usr/bin/python2.7, Python 2.7.15+, python-minimal, 2.7.15-3
SourcePackage: zim
Tags: third-party-packages cosmic
Title: zim crashed with TypeError in on_add_new_column(): Gtk.TreeView.set_cursor_on_cell() takes exactly 5 non-keyword arguments (3 given)
Uname: Linux 4.18.0-17-generic x86_64
UnreportableReason: Этот пакет не является официальным пакетом Ubuntu. Пожалуйста, удалите все сторонние пакеты и попробуйте снова.
UpgradeStatus: Upgraded to cosmic on 2018-11-13 (145 days ago)
_MarkForUpload: True

**Comment by jaap-karssenberg** [comment]
@Nick222 could you confirm whether this one is now fixed ?  Thanks

**Comment by Nick222** [comment]
But where I can get new version of Zim ?

**Comment by jaap-karssenberg** [comment]
If you use the snapshot PPA it will build daily. Or you can grab the source directly from github.

**Comment by Nick222** [comment]
Zim version from snapshot PPA:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 662, in on_clone_row
    model.insert_after(treeiter, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1026, in insert_after
    return self._do_insert(position, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 989, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 888, in _convert_row
    if len(row) != n_columns:
TypeError: object of type 'TreeModelRow' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 662, in on_clone_row
    model.insert_after(treeiter, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1026, in insert_after
    return self._do_insert(position, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 989, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 888, in _convert_row
    if len(row) != n_columns:
TypeError: object of type 'TreeModelRow' has no len()

DEBUG: Store page in background: *****
DEBUG: Index file: *****

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 662, in on_clone_row
    model.insert_after(treeiter, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1026, in insert_after
    return self._do_insert(position, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 989, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 888, in _convert_row
    if len(row) != n_columns:
TypeError: object of type 'TreeModelRow' has no len()

DEBUG: Store page in background: *****
DEBUG: Index file: *****

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 662, in on_clone_row
    model.insert_after(treeiter, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1026, in insert_after
    return self._do_insert(position, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 989, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 888, in _convert_row
    if len(row) != n_columns:
TypeError: object of type 'TreeModelRow' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/tableeditor.py", line 662, in on_clone_row
    model.insert_after(treeiter, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1026, in insert_after
    return self._do_insert(position, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 989, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 888, in _convert_row
    if len(row) != n_columns:
TypeError: object of type 'TreeModelRow' has no len()

Error window:

Package: zim 0.70-SNAPSHOT-t201904111929~ubuntu18.10.1 [origin: LP-PPA-jaap.karssenberg-zim-snapshots]
PackageArchitecture: all
ProcCpuinfoMinimal:
 processor	: 3
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 30
 model name	: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
 stepping	: 5
 microcode	: 0xa
 cpu MHz		: 2525.952
 cache size	: 8192 KB
 physical id	: 0
 siblings	: 4
 core id		: 3
 cpu cores	: 4
 apicid		: 6
 initial apicid	: 6
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 11
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
 bogomips	: 5619.38
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 36 bits physical, 48 bits virtual
 power management:
ProcVersionSignature: Ubuntu 4.18.0-17.18-generic 4.18.20
Python3Details: /usr/bin/python3.6, Python 3.6.7, python3-minimal, 3.6.7-1~18.10
PythonDetails: /usr/bin/python2.7, Python 2.7.15+, python-minimal, 2.7.15-3
SourcePackage: zim
Tags: third-party-packages cosmic
Title: zim crashed with TypeError in _convert_row(): object of type 'TreeModelRow' has no len()
Uname: Linux 4.18.0-17-generic x86_64
UnreportableReason: Этот пакет не является официальным пакетом Ubuntu. Пожалуйста, удалите все сторонние пакеты и попробуйте снова.
UpgradeStatus: Upgraded to cosmic on 2018-11-13 (149 days ago)
_MarkForUpload: True

**Comment by Nick222** [comment]
And command from RightMouseButton (on table) - Duplucate Row - do not work at all.

**Comment by jaap-karssenberg** [comment]
Thank you for the updates. But can you confirm whether your previous issue
with insert table is fixed now ?

Thanks,

Jaap

**Comment by Nick222** [comment]
Yes, crash after inserting table I cannot see...
