### ISSUE TITLE
Zim and Zim-clip error

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#784]
Xubuntu 18.10
Zim 0.70 from snapshot 11.04.2019
Firefox 66.0.2
Zim-clip plugin for Firefox 1.3
Zim-clip plugin for Zim 1.3

I create by Zim-clip in Firefox link for insert in Zim-notebook.
Then insert it on default page in Zim-notebook.
All OK.
Then I cut this link from default page - go to special page - and insert link on it.

Error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4612, in do_delete_range
    self.flush_insert()
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4602, in flush_insert
    if not _flush_group(self.stack[i]):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 4593, in _flush_group
    tree = self.buffer.get_parsetree(bounds, raw=True)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 2404, in get_parsetree
    anchor.dump(builder)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 6608, in dump
    builder.append(LINE, '-'*20) # FIXME: why do we need text here?
AttributeError: 'xml.etree.ElementTree.TreeBuilder' object has no attribute 'append'

(zim:19966): Gtk-WARNING **: 19:20:20.681: gtk_widget_size_allocate(): attempt to allocate widget with width 874 and height -1

(zim:19966): Gtk-WARNING **: 19:20:20.681: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node box, owner GtkVBox)

(two last line many times)

Crash report:

Package: zim 0.70-SNAPSHOT-t201904111929-ubuntu18.10.1 [origin: LP-PPA-jaap.karssenberg-zim-snapshots]
PackageArchitecture: all
ProcCpuinfoMinimal:
 processor	: 3
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 30
 model name	: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
 stepping	: 5
 microcode	: 0xa
 cpu MHz		: 2824.679
 cache size	: 8192 KB
 physical id	: 0
 siblings	: 4
 core id		: 3
 cpu cores	: 4
 apicid		: 6
 initial apicid	: 6
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 11
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
 bogomips	: 5619.38
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 36 bits physical, 48 bits virtual
 power management:
ProcVersionSignature: Ubuntu 4.18.0-17.18-generic 4.18.20
Python3Details: /usr/bin/python3.6, Python 3.6.7, python3-minimal, 3.6.7-1~18.10
PythonDetails: /usr/bin/python2.7, Python 2.7.15+, python-minimal, 2.7.15-3
SourcePackage: zim
Tags: third-party-packages cosmic
Title: zim crashed with AttributeError in dump(): 'xml.etree.ElementTree.TreeBuilder' object has no attribute 'append'
Uname: Linux 4.18.0-17-generic x86_64
UnreportableReason: Этот пакет не является официальным пакетом Ubuntu. Пожалуйста, удалите все сторонние пакеты и попробуйте снова.
UpgradeStatus: Upgraded to cosmic on 2018-11-13 (149 days ago)
_MarkForUpload: True

Are there error of Zim or error of zim-plugin ?

**Comment by Nick222** [comment]
I paste in note in Zim this

[[https://chrdk.ru/news/v_marianskoi_vpadine_nashli_nebyvaloe_kolichestvo_razlagayushchih_uglevodorody_bakterii|В Марианской впадине нашли небывалое количество разлагающих углеводороды бактерий]]

and it converting to this

[[https://chrdk.ru/news/v_marianskoi_vpadine_nashli_nebyvaloe_kolichestvo_razlagayushchih_uglevodorody_bakterii|%D0%92 Марианской впадине нашли небывалое количество разлагающих углеводороды бактерий]]
