### ISSUE TITLE
Can't delete pages

### ISSUE THREAD

**Issue by jhe-** [zim-desktop-wiki/zim-desktop-wiki#798]
Using version 0.70 on Ubuntu 18.04.

With a fresh index.db and state.conf, newly created pages cannot be deleted with Zim. This happens when pressing Delete in either the left or top pane, and persists after restarting Zim. The only way I can currently delete such pages is by removing the text file, and pressing `Ctrl+R` to reload.

![Peek 2019-04-15 18-44](https://user-images.githubusercontent.com/4308710/56176114-ddb3b100-5fae-11e9-9815-c272f73a6a9b.gif)

Upon closer inspection, the traceback looks like this:
```
INFO: Move /home/jhe/Dropbox/Zim/test1.txt to trash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 242, in <lambda>
    GObject.idle_add(lambda: next(my_iter, False), priority=GObject.PRIORITY_LOW)
  File "/usr/lib/python3/dist-packages/zim/notebook/operations.py", line 262, in __iter__
    progress = next(self._do_work)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 938, in trash_page_iter
    self._trash_page(path)
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 963, in _trash_page
    re = helper.trash(file) or re
  File "/usr/lib/python3/dist-packages/zim/newfs/helpers.py", line 88, in trash
    raise error
  File "/usr/lib/python3/dist-packages/zim/newfs/helpers.py", line 78, in trash
    ok = f.trash()
GLib.Error: g-io-error-quark: Unable to find or create trash directory for /home/jhe/Dropbox/Zim/test1.txt (0)
INFO: No VCS detected
INFO: Open page: Home (Home)
INFO: Loading template from: /usr/share/zim/templates/wiki/Default.txt
```

This showstopper problem seems to have gotten more severe since 0.68.rc1.

**Comment by jhe-** [comment]
**Please disregard, my system Trash folder did not have the correct permissions for some reason.**

For this rare occurrence, it would be ideal to print a helpful error message like file managers do, but obviously this is not high priority.

![image](https://user-images.githubusercontent.com/4308710/56177460-8fed7780-5fb3-11e9-90fc-350a078bcb33.png)
