### ISSUE TITLE
Zim crash in zim 0.68

### ISSUE THREAD

**Issue by msnjuegos** [zim-desktop-wiki/zim-desktop-wiki#809]
Here is the output from debug:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/gui/pageindex.py", line 249, in on_iter_children
    return self.on_get_iter(treepath)
  File "/usr/lib/python2.7/dist-packages/zim/gui/pageindex.py", line 224, in on_get_iter
    return self.get_mytreeiter(treepath)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/tags.py", line 567, in get_mytreeiter
    offset = treepath[-1]
TypeError: an integer is required

```
 I think that it's related to tag's plugin because I was deleting tags and updating index (Tools --> Update Index) and  Reload (CTRL+R) the page to see the changes, but it crashed randomly. 

Thanks in advance

**Comment by jonasstein** [comment]
0.68 is very old. Could you retry with a recent version, please?

**Comment by msnjuegos** [comment]
It's the stable version for Debian 10 (Buster) :/. But I haven't had this error again, so I will proceed to close this issue.
