### ISSUE TITLE
Plugin-Development: Cannot import name NotebookExtension

### ISSUE THREAD

**Issue by pschwede** [zim-desktop-wiki/zim-desktop-wiki#813]
I'm unsure whether to post it here rather than in a chat. Ah never mind, here it is.

Running Zim 0.69.1 with an additional plugin (wip adaptation of the Journal-Plugin) I get this message in `--verbose` mode:

```
ERROR: Could not load plugin AdaptedJournal
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/gui/preferencesdialog.py", line 323, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python2.7/dist-packages/zim/plugins/__init__.py", line 211, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python2.7/dist-packages/zim/utils/__init__.py", line 39, in get_module
    mod = __import__(name)
  File "/home/peter/.local/share/zim/plugins/AdaptedJournal.py", line 16, in <module>
    from zim.notebook import Path, NotebookExtension
    from zim.notebook import Path, NotebookExtension
ImportError: cannot import name NotebookExtension
```

What should I do?

**Comment by jaap-karssenberg** [comment]
You might be caught up between incompatible versions.

* As of zim 0.70 you import the NotebookExtension class from the
zim.notebook module. However in zim 0.69 it is defined in the zim.plugins
module.
* Also Zim 0.69 uses python2 and Gtk2, Zim 0.70 uses python3 and Gtk3

I would strongly recommend using zim 0.70 or 0.71 (released yesterday) to
develop new plugins.

Regards,

Jaap

**Comment by pschwede** [comment]
Good point.
