### ISSUE TITLE
[abrt] Zim: decode(): local.py:310:read:zim.newfs.base.FileUnicodeError

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#829]
[abrt] Zim: decode(): local.py:310:read:zim.newfs.base.FileUnicodeError: Impossible de lire : /home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt

https://bugzilla.redhat.com/show_bug.cgi?id=1704235

```
Description of problem:
I was exporting all my Zim notebook to a folder in html format when Zim crashed. 
I got few pages but a major part of my notebook is absent.

I got a success message but I didn't work correctly.

Version-Release number of selected component:
Zim-0.70-1.fc30

Additional info:
reporter:       libreport-2.10.0
cmdline:        /usr/bin/python3 /usr/bin/zim
crash_function: decode
exception_type: UnicodeDecodeError
executable:     /usr/bin/zim
interpreter:    python3-3.7.3-1.fc30.x86_64
kernel:         5.0.7-300.fc30.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
local.py:310:read:zim.newfs.base.FileUnicodeError: Impossible de lire : /home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt

Ceci signifie généralement que le fichier contient des caractères invalides

Détails:
'utf-8' codec can't decode byte 0xe9 in position 208: invalid continuation byte


Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/zim/newfs/local.py", line 308, in read
    text = fh.read()
  File "/usr/lib64/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 208: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/zim/notebook/operations.py", line 242, in <lambda>
    GObject.idle_add(lambda: next(my_iter, False), priority=GObject.PRIORITY_LOW)
  File "/usr/lib/python3.7/site-packages/zim/notebook/operations.py", line 262, in __iter__
    progress = next(self._do_work)
  File "/usr/lib/python3.7/site-packages/zim/export/exporters/files.py", line 104, in export_iter
    self.export_page(pages.notebook, page, pages, prevpage=prev, nextpage=next)
  File "/usr/lib/python3.7/site-packages/zim/export/exporters/files.py", line 140, in export_page
    title=page.get_title(),
  File "/usr/lib/python3.7/site-packages/zim/notebook/page.py", line 720, in get_title
    tree = self.get_parsetree()
  File "/usr/lib/python3.7/site-packages/zim/notebook/page.py", line 565, in get_parsetree
    text, self._last_etag = self.source_file.read_with_etag()
  File "/usr/lib/python3.7/site-packages/zim/newfs/base.py", line 694, in read_with_etag
    return self._read_with_etag(self.read)
  File "/usr/lib/python3.7/site-packages/zim/newfs/base.py", line 701, in _read_with_etag
    content = func()
  File "/usr/lib/python3.7/site-packages/zim/newfs/local.py", line 310, in read
    raise FileUnicodeError(self, err)
zim.newfs.base.FileUnicodeError: Impossible de lire : /home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt

Ceci signifie généralement que le fichier contient des caractères invalides

Détails:
'utf-8' codec can't decode byte 0xe9 in position 208: invalid continuation byte


Local variables in innermost frame:
self: <LocalFile: /home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt>
fh: <_io.TextIOWrapper name='/home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt' mode='r' encoding='UTF-8'>

```

**Comment by introt** [comment]
Can you please test this with 0.74? Please post the offending (part of the) file `/home/amasson/Documents/Documentation/doc_t2t/textallion/contrib/inno_setup/textallion_setup/readmeFR.txt`

**Comment by introt** [comment]
@cheese please reopen & post excerpt of file if this is still happening on >0.74, thanks
