### ISSUE TITLE
Zim can't start - ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by quatran** [zim-desktop-wiki/zim-desktop-wiki#976]
Zim crahes at start.  I use openSUSE Tumbleweed and the version of zim is 0.72.0-1.1. If you need more infos let me know.

```Traceback (most recent call last):
File "/usr/bin/zim", line 40, in <module>
    import zim.main
  File "/usr/lib/python3.7/site-packages/zim/main/__init__.py", line 31, in <module>
    from zim.notebook import Notebook, Path, \
  File "/usr/lib/python3.7/site-packages/zim/notebook/__init__.py", line 38, in <module>
    from .info import NotebookInfo, NotebookInfoList, \
  File "/usr/lib/python3.7/site-packages/zim/notebook/info.py", line 18, in <module>
    from .notebook import NotebookConfig, _resolve_relative_config
  File "/usr/lib/python3.7/site-packages/zim/notebook/notebook.py", line 17, in <module>
    import zim.templates
  File "/usr/lib/python3.7/site-packages/zim/templates/__init__.py", line 61, in <module>
    from zim.templates.functions import build_template_functions
  File "/usr/lib/python3.7/site-packages/zim/templates/functions.py", line 24, in <module>
    from zim.formats.html import html_encode
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 79, in <module>
    from zim.plugins import PluginManager
  File "/usr/lib/python3.7/site-packages/zim/plugins/__init__.py", line 45, in <module>
    from zim.actions import hasaction
  File "/usr/lib/python3.7/site-packages/zim/actions.py", line 36, in <module>
    PRIMARY_MODIFIER_MASK = _get_modifier_mask()
  File "/usr/lib/python3.7/site-packages/zim/actions.py", line 30, in _get_modifier_mask
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available```

**Comment by quatran** [comment]
After installing the packages 'gtk3-devel' and python3-gobject-Gdk', zim can finally start.

**Comment by sf9v** [comment]
@quatran thanks, it worked. Have any idea why the required packages are not included in the zim install?
