### ISSUE TITLE
Can't use non ASCII characters in custom tools command

### ISSUE THREAD

**Issue by Self-Perfection** [zim-desktop-wiki/zim-desktop-wiki#982]
Zim 0.72, Arch linux

Attempt to save custom tool with non ASCII characters in command gives error
```
DEBUG: Closed dialog "Edit Custom Tool"
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/gui/applications.py", line 675, in check
    x = value.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-11: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/config/dicts.py", line 532, in __setitem__
    v = self.definitions[k].check(v)
  File "/usr/lib/python3.8/site-packages/zim/gui/applications.py", line 677, in check
    raise ValueError('ASCII string required')
ValueError: ASCII string required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/gui/customtools.py", line 554, in on_edit
    tool.update(**properties)
  File "/usr/lib/python3.8/site-packages/zim/gui/customtools.py", line 324, in update
    self['Desktop Entry'].update(E, **F)
  File "/usr/lib/python3.8/site-packages/zim/config/dicts.py", line 507, in update
    ControlledDict.update(self, E, **F)
  File "/usr/lib/python3.8/site-packages/zim/config/dicts.py", line 86, in update
    OrderedDict.update(self, E, **F)
  File "/usr/lib/python3.8/_collections_abc.py", line 840, in update
    self[key] = value
  File "/usr/lib/python3.8/site-packages/zim/config/dicts.py", line 534, in __setitem__
    raise ValueError('Invalid config value for %s: "%s" - %s' % (k, v, error.args[0]))
ValueError: Invalid config value for X-Zim-ExecTool: "echo 'Привет, мир'" - ASCII string required
```

**Comment by introt** [comment]
Same error, but fails silently on 0.74

**Comment by introt** [comment]
Found this patch, seems to imply `sys.getfilesystemencoding()` is at fault here: https://github.com/Osndok/zim-desktop-wiki/commit/d65338838fc0c39861bf475ba4b65b6cfef63d56

**Comment by Self-Perfection** [comment]
Had a proper look at this. The rejection is zim's own code, it is deliberate, and it comes from reading the Desktop Entry Specification literally - but it is applied to a key that the specification does not actually govern. All references below point at 0.77.2 (`51937eb4`).

## Where the value is rejected

The config value type that enforces it:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/gui/applications.py#L788-L800

and the command key of a custom tool is declared with that type:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/gui/customtools.py#L250-L256

The failure itself happens in [`ConfigDict.__setitem__()`](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/config/dicts.py#L647-L655), before the command reaches anything else. No external component is involved - `subprocess`, GLib and the filesystem all handle UTF-8 here without complaint.

## Where the rule comes from

The table of key types is introduced with the comment *"Data types for all keys are defined in spec - see freedesktop.org"*:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/gui/applications.py#L880-L892

And the specification does say this (Desktop Entry Specification, section 4, "Possible value types"):

> Values of type **string** may contain all **ASCII** characters except for control characters.
> Values of type **localestring** are user displayable, and are encoded in **UTF-8**.

The `Exec` key is listed as type `string`, so for a real desktop entry the restriction is genuine. Zim simply implements it.

## History

The check arrived in 0137fb2e (2013-12-06), *"Made ConfigDict enforce type of config keys"*. The commit message does not discuss this specific key. On Python 2 it was written differently:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/0137fb2ee1caccb81dd1200ab3673b07212d100a/zim/gui/applications.py#L354-L362

That rejected non-ASCII just the same, via the implicit ASCII decode in the comparison. The Python 3 port only made the intent explicit. So this is not a porting regression - the behaviour has been the same since 2013.

## Why this looks like a misapplication

`X-Zim-ExecTool` is not the spec's `Exec` key. It is a vendor extension in the sense of section 12 of the specification:

> If one particular party wishes to add a field for personal use, they should prefix the key with the string `X-PRODUCT`, e.g. `X-NewDesktop-Foo`.

The specification defines the naming mechanism for such keys, but their value type is the vendor's choice. `String` here looks like it was picked by analogy with `Exec` rather than because the spec requires it.

On top of that, a custom tool file is not a desktop entry that anything else can consume:

- `Type=X-Zim-CustomTool`, not `Application`;
- the actual `Exec` key is written **empty** - [an empty string is passed on creation](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/gui/customtools.py#L147), the real command lives only in `X-Zim-ExecTool`;
- `NoDisplay` is set, and the file lives in `~/.config/zim/customtools/`.

So no XDG desktop entry parser ever reads these files, and the ASCII restriction buys nothing.

A useful cross-check: `Name` and `Comment` are declared as [`LocaleString`](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/gui/applications.py#L803-L804), so non-ASCII in the tool *name* already works today. Only the command is rejected.

## Why it "fails silently" on newer versions (@introt)

The write path and the read path handle the same `ValueError` differently. Saving from the dialog goes through `ConfigDict.__setitem__()`, which re-raises - that is the traceback in this ticket. Reading a file goes through `_set_input()`, which logs a warning and falls back to the default:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/51937eb4afce1047e445b605289810cc39fd176c/zim/config/dicts.py#L722-L739

So hand-editing the `.desktop` file does not raise - the tool is just loaded with an empty command.

## About the patch linked above

The referenced commit in the Osndok fork is unrelated: it changes how `sys.argv` was decoded in the Python 2 `zim.py`. That code no longer exists - `getfilesystemencoding` does not appear anywhere in the current tree.

## Possible fix

Declaring the key as `LocaleString(None)` instead of `String(None)` should be enough - `LocaleString` is `pass # utf8 already supported by default`, it adds no other behaviour. Worth checking how that interacts with the `[lang]` key selectors, so the change does not accidentally make the key localizable.

Happy to prepare a patch if that direction looks right.
